/**
 * Locator expressions run against `pages/locator-kinds.html`, grouped by the
 * locator kind they exercise. Written in the canonical form the test runner
 * prints (and the locator index stores): no `page.` prefix.
 */
export const LOCATOR_CASES: Record<string, string[]> = {
  'getByRole: names and buttons': [
    "getByRole('button')",
    "getByRole('button', { name: 'Add to cart' })",
    "getByRole('button', { name: 'add to cart' })",
    "getByRole('button', { name: 'Add to cart', exact: true })",
    "getByRole('button', { name: 'add to cart', exact: true })",
    "getByRole('button', { name: /add/i })",
    "getByRole('button', { name: /^Add/ })",
    "getByRole('button', { name: /cart$/ })",
    "getByRole('button', { name: 'Save' })",
    "getByRole('button', { name: 'Favorite' })",
    "getByRole('button', { name: 'Favorite', exact: true })",
    "getByRole('button', { name: 'Mark done' })",
    "getByRole('button', { name: '✓' })",
    "getByRole('button', { name: 'Starred' })",
    "getByRole('button', { name: 'Step Two' })",
    "getByRole('button', { name: 'Step Two', exact: true })",
    "getByRole('button', { name: 'Gear' })",
    "getByRole('button', { name: 'Trash Delete' })",
    "getByRole('button', { name: 'Delete' })",
    "getByRole('button', { name: 'Delete', exact: true })",
    "getByRole('button', { name: 'Place order' })",
    "getByRole('button', { name: 'Submit' })",
    "getByRole('button', { name: 'Reset' })",
    "getByRole('button', { name: 'Preview' })",
    "getByRole('button', { name: 'Pay with card' })",
    "getByRole('button', { name: 'Attachment' })",
    "getByRole('button', { name: 'Refresh the list' })",
    "getByRole('button', { name: '⟳' })",
    "getByRole('button', { name: 'Help' })",
    "getByRole('button', { name: 'Card menu' })",
    "getByRole('button', { name: 'Slotted action' })",
    "getByRole('button', { name: 'Shadow button' })",
    "getByRole('button', { name: 'Nested shadow button' })",
    "getByRole('button', { name: 'Closed shadow button' })",
    "getByRole('BUTTON', { name: 'Pay now' })",
    "getByRole('button', { name: '' })",
    "getByRole('button', { name: '  pay   NOW ' })",
  ],
  'getByRole: states': [
    "getByRole('button', { disabled: true })",
    "getByRole('button', { disabled: false })",
    "getByRole('button', { pressed: true })",
    "getByRole('button', { pressed: false })",
    "getByRole('button', { expanded: false })",
    "getByRole('button', { name: 'Compare', pressed: true })",
    "getByRole('button', { name: 'Help', disabled: false })",
    "getByRole('button', { name: 'Send invoice', disabled: true })",
    "getByRole('button', { name: 'Underline', disabled: true })",
    "getByRole('button', { name: 'Italic', disabled: true })",
    "getByRole('button', { name: 'Save draft', description: 'Keeps your changes for later' })",
    "getByRole('button', { description: 'Opens the settings panel' })",
    "getByRole('button', { description: /settings/ })",
    "getByRole('button', { description: 'Mark done' })",
    "getByRole('checkbox')",
    "getByRole('checkbox', { checked: true })",
    "getByRole('checkbox', { checked: false })",
    "getByRole('checkbox', { name: 'I accept the terms' })",
    "getByRole('checkbox', { name: 'Select all' })",
    "getByRole('checkbox', { name: 'Select all', checked: false })",
    "getByRole('checkbox', { name: 'Some selected' })",
    "getByRole('switch', { checked: true })",
    "getByRole('radio')",
    "getByRole('radio', { checked: true })",
    "getByRole('radio', { name: 'PayPal' })",
    "getByRole('radio', { name: 'Wire transfer', disabled: true })",
    "getByRole('option', { selected: true })",
    "getByRole('option', { name: 'Germany', selected: true })",
    "getByRole('option', { name: 'Narnia', disabled: true })",
    "getByRole('menuitemcheckbox', { checked: true })",
    "getByRole('menuitemradio', { checked: false })",
    "getByRole('tab', { selected: true })",
    "getByRole('tab', { name: 'Map', disabled: true })",
    "getByRole('treeitem', { level: 2 })",
    "getByRole('treeitem', { expanded: true })",
    "getByRole('treeitem', { selected: true })",
    "getByRole('heading', { level: 1 })",
    "getByRole('heading', { level: 2 })",
    "getByRole('heading', { level: 3 })",
    "getByRole('heading', { name: 'Delivery options', level: 3 })",
    "getByRole('gridcell', { selected: true })",
    "getByRole('row', { selected: true })",
    "getByRole('button', { checked: true })",
    "getByRole('link', { level: 1 })",
  ],
  'getByRole: hidden elements': [
    "getByRole('button', { includeHidden: true })",
    "getByRole('button', { name: 'Gone button' })",
    "getByRole('button', { name: 'Gone button', includeHidden: true })",
    "getByRole('button', { name: 'Ghost button' })",
    "getByRole('button', { name: 'Ghost button', includeHidden: true })",
    "getByRole('button', { name: 'Aria hidden button' })",
    "getByRole('button', { name: 'Aria hidden button', includeHidden: true })",
    "getByRole('button', { name: 'Hidden attribute button', includeHidden: true })",
    "getByRole('button', { name: 'Transparent button' })",
    "getByRole('button', { name: 'Offscreen button' })",
    "getByRole('button', { name: 'Zero box button' })",
    "getByRole('button', { name: 'Contents child button' })",
    "getByRole('button', { name: 'Inside details' })",
    "getByRole('button', { name: 'Inside details', includeHidden: true })",
    "getByRole('button', { name: 'Visible in details' })",
    "getByRole('link', { name: 'Gone link' })",
    "getByRole('link', { name: 'Gone link', includeHidden: true })",
  ],
  'getByRole: fields and widgets': [
    "getByRole('textbox')",
    "getByRole('textbox', { name: 'First name' })",
    "getByRole('textbox', { name: 'Last name' })",
    "getByRole('textbox', { name: 'Email address' })",
    "getByRole('textbox', { name: 'Phone (mobile)' })",
    "getByRole('textbox', { name: 'Phone' })",
    "getByRole('textbox', { name: 'Company name' })",
    "getByRole('textbox', { name: 'Company (optional)' })",
    "getByRole('textbox', { name: 'VAT number' })",
    "getByRole('textbox', { name: 'Password' })",
    "getByRole('textbox', { name: 'Delivery notes' })",
    "getByRole('textbox', { name: 'Invoice email', disabled: true })",
    "getByRole('textbox', { name: 'Shadow field' })",
    "getByRole('textbox', { name: 'Delivery date' })",
    "getByRole('searchbox')",
    "getByRole('searchbox', { name: 'Search' })",
    "getByRole('combobox')",
    "getByRole('combobox', { name: 'Country' })",
    "getByRole('combobox', { name: 'City' })",
    "getByRole('combobox', { name: 'Flavor' })",
    "getByRole('listbox')",
    "getByRole('listbox', { name: 'Tags' })",
    "getByRole('option')",
    "getByRole('option', { name: 'Medium' })",
    "getByRole('spinbutton', { name: 'Quantity' })",
    "getByRole('slider', { name: 'Tip' })",
    "getByRole('group', { name: 'Payment method' })",
    "getByRole('group')",
    "getByRole('radiogroup')",
    "getByRole('progressbar', { name: 'Upload' })",
    "getByRole('meter')",
    "getByRole('status')",
    "getByRole('link')",
    "getByRole('link', { name: 'Products' })",
    "getByRole('link', { name: 'My account' })",
    "getByRole('link', { name: 'Acme home' })",
    "getByRole('link', { name: 'Not a link' })",
    "getByRole('link', { name: 'Archive' })",
    "getByRole('menuitem', { name: 'Archive' })",
    "getByRole('menuitem')",
    "getByRole('menu', { name: 'Actions' })",
    "getByRole('tab')",
    "getByRole('tablist', { name: 'Views' })",
    "getByRole('tree')",
    "getByRole('toolbar')",
  ],
  'getByRole: structure and landmarks': [
    "getByRole('heading')",
    "getByRole('heading', { name: 'Gift wrapping' })",
    "getByRole('heading', { name: 'Shadow heading' })",
    "getByRole('heading', { name: 'Slotted title' })",
    "getByRole('heading', { name: 'Green mug new' })",
    "getByRole('heading', { name: 'Card details' })",
    "getByRole('form')",
    "getByRole('form', { name: 'Shipping address' })",
    "getByRole('region')",
    "getByRole('region', { name: 'Products' })",
    "getByRole('navigation', { name: 'Main' })",
    "getByRole('main')",
    "getByRole('banner')",
    "getByRole('contentinfo')",
    "getByRole('complementary')",
    "getByRole('search')",
    "getByRole('article')",
    "getByRole('list')",
    "getByRole('listitem')",
    "getByRole('table')",
    "getByRole('table', { name: 'Orders' })",
    "getByRole('grid', { name: 'Seats' })",
    "getByRole('gridcell')",
    "getByRole('cell')",
    "getByRole('cell', { name: 'Shipped' })",
    "getByRole('columnheader')",
    "getByRole('rowheader')",
    "getByRole('row')",
    "getByRole('row', { name: '#1001 Shipped 42 €' })",
    "getByRole('rowgroup')",
    "getByRole('dialog')",
    "getByRole('dialog', { name: 'Confirm deletion' })",
    "getByRole('alert')",
    "getByRole('img')",
    "getByRole('img', { name: 'Chart' })",
    "getByRole('img', { name: 'Gear' })",
    "getByRole('img', { name: 'Logo mark' })",
    "getByRole('presentation')",
    "getByRole('none')",
    "getByRole('term')",
    "getByRole('definition')",
    "getByRole('separator')",
    "getByRole('paragraph')",
    "getByRole('emphasis')",
    "getByRole('strong')",
    "getByRole('document')",
    "getByRole('generic')",
    "getByRole('iframe')",
  ],
  getByText: [
    "getByText('Hello')",
    "getByText('Hello world')",
    "getByText('world')",
    "getByText('Hello world, welcome back!', { exact: true })",
    "getByText('hello world, welcome back!', { exact: true })",
    'getByText(/welcome/)',
    'getByText(/WELCOME/i)',
    'getByText(/^Hello/)',
    "getByText('Lots of spaces')",
    "getByText('Lots of spaces', { exact: true })",
    "getByText('Non breaking space')",
    "getByText('Zerowidth')",
    "getByText('Line break')",
    "getByText('Linebreak')",
    "getByText('Café')",
    "getByText('cafe')",
    "getByText('straße')",
    "getByText('Quote \\' and')",
    "getByText('Emoji 🎉')",
    "getByText('Split across')",
    "getByText('Parent text')",
    "getByText('child text')",
    "getByText('Only child')",
    "getByText('Only child', { exact: true })",
    "getByText('Hidden script text')",
    "getByText('color: red')",
    "getByText('Gone button')",
    "getByText('Ghost text')",
    "getByText('Place order')",
    "getByText('Submit')",
    "getByText('Shadow button')",
    "getByText('Deep text')",
    "getByText('Closed shadow button')",
    "getByText('Slotted title')",
    "getByText('Card menu')",
    "getByText('Pay 42 €')",
    "getByText('Status: OK')",
    "getByText('OK')",
    "getByText('Add to cart')",
    "getByText('mug')",
    "getByText('€')",
    "getByText('#1002')",
    "getByText('Order #1002 is pending', { exact: true })",
    "getByText('Payment failed')",
    'getByText(/\\d+ €/)',
    "getByText('')",
  ],
  'getByLabel, getByPlaceholder, getByAltText, getByTitle': [
    "getByLabel('First name')",
    "getByLabel('first NAME')",
    "getByLabel('First name', { exact: true })",
    "getByLabel('Last name')",
    "getByLabel('Last name', { exact: true })",
    "getByLabel('Email address')",
    "getByLabel('Phone')",
    "getByLabel('(mobile)')",
    "getByLabel('Country')",
    "getByLabel('Tags')",
    "getByLabel('City')",
    "getByLabel('Delivery notes')",
    "getByLabel('Card')",
    "getByLabel('PayPal')",
    "getByLabel('I accept the terms')",
    "getByLabel('Select all')",
    "getByLabel('Quantity')",
    "getByLabel('Search')",
    "getByLabel('Main')",
    "getByLabel('Products')",
    "getByLabel('Shipping address')",
    "getByLabel('Shadow field')",
    'getByLabel(/name/i)',
    'getByLabel(/^Phone/)',
    "getByLabel('Favorite')",
    "getByLabel('Nothing like this')",
    "getByPlaceholder('Doe')",
    "getByPlaceholder('doe')",
    "getByPlaceholder('Doe', { exact: true })",
    "getByPlaceholder('doe', { exact: true })",
    "getByPlaceholder('you@example')",
    "getByPlaceholder('Company')",
    'getByPlaceholder(/number/i)',
    "getByPlaceholder('Search products')",
    "getByPlaceholder('Inside shadow')",
    "getByPlaceholder('Leave at the door', { exact: true })",
    "getByAltText('Acme home')",
    "getByAltText('acme')",
    "getByAltText('Trash', { exact: true })",
    'getByAltText(/card/)',
    "getByAltText('Pay with card')",
    "getByTitle('Company name')",
    "getByTitle('Mark done')",
    "getByTitle('refresh')",
    "getByTitle('Chart', { exact: true })",
    'getByTitle(/payment/i)',
  ],
  getByTestId: [
    "getByTestId('pay')",
    "getByTestId('pay-later')",
    "getByTestId('Pay')",
    "getByTestId('promo')",
    "getByTestId('Promo')",
    'getByTestId(/pay/)',
    "getByTestId('shadow-btn')",
    "getByTestId('card-host')",
    "getByTestId('first-name')",
    "getByTestId('shipping-form')",
    "getByTestId('card-number')",
    "getByTestId('status')",
  ],
  'locator: CSS': [
    "locator('button')",
    "locator('.card')",
    "locator('.card .add')",
    "locator('.card > .add')",
    "locator('h3 + p')",
    "locator('h3 ~ button')",
    "locator('#first')",
    'locator(\'[name="email"]\')',
    "locator('input[type=checkbox]:checked')",
    "locator('li:nth-child(2)')",
    "locator('button:not([disabled])')",
    "locator('.card:has(button[aria-pressed])')",
    "locator('section button, nav a')",
    "locator('nav a, section button')",
    "locator('#shadow-host button')",
    "locator('#shadow-host .inner > button')",
    "locator('.inner')",
    "locator('x-card button')",
    "locator('x-card section button')",
    "locator('*')",
    "locator('main > *')",
    "locator('body div')",
    'locator(\'button:has-text("Add")\')',
    'locator(\'button:has-text("add to cart")\')',
    'locator(\'article:has-text("Red mug")\')',
    'locator(\'p:text("welcome")\')',
    'locator(\':text("Only child")\')',
    'locator(\'span:text-is("Only child")\')',
    'locator(\':text-matches("Hel+o", "i")\')',
    "locator('button:visible')",
    "locator('.hidden-cases button:visible')",
    "locator('.hidden-cases button')",
    'locator(\'div:has-text("Payment failed")\')',
    "locator('invalid[[[')",
    "locator('button:nth-match(2)')",
  ],
  'locator: selector engines': [
    "locator('text=Add to cart')",
    'locator(\'text="Add to cart"\')',
    'locator("text=\'Only child\'")',
    "locator('text=/mug/i')",
    'locator(\'"Place order"\')',
    "locator('xpath=//button')",
    "locator('//h3')",
    "locator('xpath=//article[2]//button')",
    "locator('id=first')",
    "locator('data-testid=pay')",
    "locator('data-test-id=banner')",
    "locator('data-test=save-address')",
    "locator('css=.price')",
    "locator('.card >> text=Add to cart')",
    "locator('.card >> nth=1')",
    "locator('button >> nth=-1')",
    "locator('button >> visible=true')",
    "locator('button >> visible=false')",
    "locator('#products >> css=h3')",
    "locator('xpath=//section >> css=button')",
  ],
  'locator: scoping and narrowing': [
    "locator('article').first()",
    "locator('article').last()",
    "locator('article').nth(1)",
    "locator('article').nth(-2)",
    "locator('article').nth(10)",
    "locator('.card', { hasText: 'Red' })",
    "locator('.card', { hasNotText: 'Red' })",
    "locator('.card', { has: getByRole('button', { name: 'Compare' }) })",
    "locator('.card', { hasNot: getByRole('button', { pressed: true }) })",
    "locator('#products').locator('h3')",
    "locator('#products').locator('article > h3')",
    "locator('#products').locator('main h3')",
    "locator('#products').locator(':scope > article')",
    "locator('#products').locator(':scope')",
    "locator('.card').locator('.price')",
    "locator('.card').getByText('Add to cart')",
    "locator('.card').getByText('12 €')",
    "locator('p.price').getByText('12 €')",
    "locator('.card').getByRole('button')",
    "locator('.card').getByRole('button', { name: 'Add to cart' }).first()",
    "locator('.card').filter({ hasText: 'Green' }).getByRole('button', { name: 'Add to cart' })",
    "locator('.card').nth(2).getByRole('button')",
    "locator('#shadow-host').getByRole('button')",
    "locator('#shadow-host').locator('button')",
    "locator('x-card').getByRole('button')",
    "locator('x-card').getByText('Slotted title')",
    "locator('x-card').locator('[slot]')",
    "locator('nav').getByRole('link')",
    "locator('select').locator('xpath=..')",
    "getByLabel('Country').locator('option')",
    "getByLabel('Country').locator('option').nth(1)",
    "getByLabel('Country').locator('xpath=./option[last()]')",
    "getByLabel('Country').locator('xpath=//option')",
    "getByRole('button').locator(getByText('Add'))",
    "locator('article').locator(getByRole('heading'))",
  ],
  'chains, filters, and/or': [
    "getByRole('form').getByLabel('Country')",
    "getByRole('form', { name: 'Shipping address' }).getByRole('textbox', { name: 'First name' })",
    "getByRole('region', { name: 'Products' }).getByRole('button', { name: 'Add to cart' })",
    "getByRole('region', { name: 'Products' }).getByRole('article').filter({ hasText: 'Blue' }).getByRole('button', { name: 'Add to cart' })",
    "getByRole('article').filter({ has: getByRole('heading', { name: 'Red mug' }) }).getByRole('button', { name: 'Compare' })",
    "getByRole('article').filter({ hasNot: getByText('new') })",
    "getByRole('article').filter({ hasText: /\\d+ €/ })",
    "getByRole('article').filter({ hasNotText: '12 €' })",
    "getByRole('article').filter({ visible: true })",
    "getByRole('button').filter({ visible: false })",
    "getByRole('button').visible()",
    "getByRole('dialog').getByRole('button', { name: 'Delete' })",
    "getByRole('table', { name: 'Orders' }).getByRole('row').filter({ hasText: 'Pending' }).getByRole('cell').first()",
    "getByRole('row', { name: '#1003' }).getByRole('button', { name: 'Refund' })",
    "getByRole('navigation').getByRole('link', { name: 'Pricing' })",
    "getByRole('tablist').getByRole('tab').nth(1)",
    "getByRole('listitem').getByRole('link')",
    "getByRole('button', { name: 'Add to cart' }).and(getByRole('button', { disabled: true }))",
    "getByRole('button', { name: 'Add to cart' }).and(locator('.add'))",
    "getByRole('button', { name: 'Pay now' }).or(getByRole('button', { name: 'Pay later' }))",
    "getByRole('button', { name: 'Pay later' }).or(getByTestId('pay'))",
    "getByText('Payment failed').or(getByRole('alert'))",
    "getByRole('button', { name: 'Nope' }).or(getByText('Hello'))",
    "locator('.card').and(getByText('Blue mug'))",
    "getByTestId('shipping-form').getByPlaceholder('Doe')",
    "getByTestId('status').getByText('OK')",
    "getByRole('group', { name: 'Payment method' }).getByRole('radio', { checked: true })",
    "getByRole('group', { name: 'Payment method' }).getByLabel('Card')",
    "locator('fieldset').filter({ has: getByText('Payment method') }).getByRole('radio')",
    "getByRole('listitem').filter({ has: getByRole('link', { name: 'Pricing' }) })",
    "getByRole('article').filter({ has: getByRole('button', { disabled: true }) }).getByRole('heading')",
    "getByRole('article').filter({ hasText: 'mug' }).filter({ hasNotText: 'Red' }).last()",
  ],
  frames: [
    "locator('#child-frame').contentFrame().getByRole('button', { name: 'Pay 42 €' })",
    "frameLocator('#child-frame').getByLabel('Card number')",
    "frameLocator('iframe').getByRole('heading')",
    "locator('#child-frame').contentFrame().getByTestId('card-number')",
    "locator('#child-frame').contentFrame().getByPlaceholder('MM/YY')",
    "locator('#child-frame').contentFrame().getByLabel('Expiry')",
    "locator('#child-frame').contentFrame().locator('#grandchild').contentFrame().getByRole('button', { name: 'Verify' })",
    "frameLocator('#child-frame').frameLocator('#grandchild').getByLabel('Code')",
    "locator('#child-frame').contentFrame().getByRole('button').or(getByText('Cancel'))",
    "locator('#child-frame').contentFrame().getByRole('button').and(getByText('Cancel'))",
    "locator('#child-frame').contentFrame().owner()",
    "frameLocator('#child-frame').owner()",
    "getByTitle('Payment frame').contentFrame().getByRole('button', { name: 'Cancel' })",
  ],
};

/** Expressions run against `pages/locator-edge-cases.html`: accessible-name, role and text corner cases. */
export const EDGE_CASES: Record<string, string[]> = {
  'names from references and embedded controls': [
    "getByRole('button', { name: 'Secret name' })",
    "getByRole('button', { name: 'Visible text' })",
    "getByRole('button', { name: 'Self extra words' })",
    "getByRole('button', { name: 'Fallback text' })",
    "getByRole('button', { name: 'Aria wins' })",
    "getByRole('button', { name: 'Blank aria label' })",
    "getByRole('spinbutton', { name: 'Quantity 3 units' })",
    "getByRole('spinbutton', { name: 'Quantity' })",
    "getByRole('combobox', { name: 'Size Large' })",
    "getByRole('combobox', { name: 'Size' })",
    "getByRole('textbox', { name: 'First label Second label' })",
    "getByRole('textbox', { name: 'Hidden part' })",
    "getByRole('textbox', { name: '(ignored)' })",
    "getByRole('button', { name: 'Inner button' })",
    "getByRole('combobox', { name: 'Pick a fruit' })",
    "getByLabel('Quantity')",
    "getByLabel('units')",
    "getByLabel('Size')",
    "getByLabel('Large')",
    "getByLabel('First label')",
    "getByLabel('Second label')",
    "getByLabel('(ignored)')",
    "getByLabel('Button label')",
    "getByLabel('Pick a fruit')",
    "getByLabel('Secret name')",
    "getByLabel('Visible text')",
  ],
  'role conflicts and inheritance': [
    "getByRole('button', { name: 'Link acting as button' })",
    "getByRole('link', { name: 'Link acting as button' })",
    "getByRole('button', { name: 'Focusable none' })",
    "getByRole('none')",
    "getByRole('presentation')",
    "getByRole('generic')",
    "getByRole('button', { name: 'First valid token' })",
    "getByRole('switch')",
    "getByRole('listitem')",
    "getByRole('cell')",
    "getByRole('region')",
    "getByRole('region', { name: 'Named section' })",
    "getByRole('form')",
    "getByRole('img')",
    "getByRole('combobox', { name: 'Search with list' })",
    "getByRole('searchbox')",
    "getByRole('listbox', { name: 'Sized select' })",
    "getByRole('button', { name: 'Summary name bold' })",
    "getByText('Loose summary')",
    "getByRole('columnheader')",
    "getByRole('rowheader')",
    "getByRole('columnheader', { name: 'Lonely header' })",
    "getByRole('list', { name: 'Owner list' })",
    "getByRole('list', { name: 'Owner list' }).getByRole('listitem')",
  ],
  'generated content, layout and SVG': [
    "getByRole('button', { name: 'Next →' })",
    "getByRole('button', { name: 'Next' })",
    "getByRole('button', { name: 'Counted' })",
    "getByRole('img', { name: 'Company logo' })",
    "getByText('Para')",
    "getByText('Text')",
    "getByRole('button', { name: 'Contents button' })",
    "getByText('Contents text')",
    "getByText('Flexitems')",
    "getByRole('button', { name: 'Inline Block' })",
    "getByRole('button', { name: 'InlineBlock' })",
    "getByRole('button', { name: 'Div stack' })",
    "getByRole('button', { name: 'Described', description: 'First part. Hidden second part.' })",
    "getByRole('button', { description: 'First part.' })",
    "getByRole('img', { name: 'Chart area' })",
    "getByRole('link', { name: 'Svg link title' })",
    "getByRole('img', { name: 'Svg title' })",
    "getByTitle('Svg link title')",
  ],
  'text and attribute subtleties': [
    "getByText('mixed case text')",
    "getByText('Mixed case TEXT', { exact: true })",
    "getByText('Outer')",
    "getByText('Outer Inner tail')",
    "getByText('Inner')",
    "getByText('Twin')",
    "getByText('Twin').nth(1)",
    "getByText('tab separated')",
    "getByText('Padded button', { exact: true })",
    "getByRole('button', { name: 'Padded button', exact: true })",
    "getByText('Spaced value', { exact: true })",
    "getByRole('button', { name: 'Spaced value', exact: true })",
    "getByText('Shadow words')",
    "getByText('Shadow')",
    "getByRole('button', { name: 'Fallback label' })",
    "getByRole('button', { name: 'Provided content' })",
    "getByText('Fallback label')",
    "locator('#fb-filled').getByRole('button')",
    "getByPlaceholder('Spaced placeholder')",
    "getByPlaceholder('Spaced placeholder', { exact: true })",
    "getByPlaceholder('mixed case')",
    "getByTitle('‘quotes’')",
    "getByAltText('ünïcödé')",
    "getByTestId('with space')",
    "getByTestId('quote\\'d')",
    "locator('[data-testid=\"quote\\'d\"]')",
    "locator('#text-parent').getByText('Inner')",
    "locator('#text-parent').getByText('Outer')",
    "locator('#text-parent >> text=Inner')",
    "locator('text=Twin >> nth=1')",
  ],
};
