import { test, expect } from './fixtures.js';
import { derivePattern } from '../../src/content/multi-pick-derive.js';
import { domRoleOf } from '@piwitests/picker-dom';
import {
  isAutoGenerated,
  classifyCssStability,
  TAG_TO_ROLE,
  INPUT_TYPE_TO_ROLE,
} from '@piwitests/core/locator-generation';
import type { Page } from '@playwright/test';

const MAPS = { tagRoles: TAG_TO_ROLE, inputRoles: INPUT_TYPE_TO_ROLE };

/**
 * `derivePattern` nests every helper inside its own body (see that function's
 * doc comment): only its genuine cross-module imports — `domRoleOf`, `isAutoGenerated`,
 * `classifyCssStability` — need installing as globals first.
 */
async function evalDerive(
  page: Page,
  selector: string,
  count: number,
): Promise<{ baseLocator: string | null; rows: { locator: string; indexBased: boolean }[] }> {
  await page.evaluate(
    ([roleSrc, autoGenSrc, stabilitySrc]) => {
      (globalThis as any).domRoleOf = new Function(`return (${roleSrc})`)();
      (globalThis as any).isAutoGenerated = new Function(`return (${autoGenSrc})`)();
      (globalThis as any).classifyCssStability = new Function(`return (${stabilitySrc})`)();
    },
    [domRoleOf.toString(), isAutoGenerated.toString(), classifyCssStability.toString()],
  );
  return page.evaluate(
    ([fnSrc, sel, n, maps]) => {
      const derive = new Function(`return (${fnSrc})`)() as (
        picked: Element[],
        m: unknown,
      ) => { baseLocator: string | null; rows: { element: Element; locator: string; indexBased: boolean }[] };
      const picked = [...document.querySelectorAll(sel)].slice(0, n);
      const result = derive(picked, maps);
      return {
        baseLocator: result.baseLocator,
        rows: result.rows.map((r) => ({ locator: r.locator, indexBased: r.indexBased })),
      };
    },
    [derivePattern.toString(), selector, count, MAPS] as const,
  );
}

test.describe('derivePattern', () => {
  test('derives a getByRole(row) pattern with per-row hasText discriminators', async ({ context }) => {
    const page = await context.newPage();
    await page.setContent(`<!doctype html><html><body>
      <table><tbody>
        <tr><td>Alice - active</td></tr>
        <tr><td>Bob - active</td></tr>
        <tr><td>Carol - suspended</td></tr>
      </tbody></table>
    </body></html>`);

    const result = await evalDerive(page, 'tr', 2);
    expect(result.baseLocator).toBe(`getByRole('row')`);
    expect(result.rows).toEqual([
      { locator: `getByRole('row').filter({ hasText: 'Alice' })`, indexBased: false },
      { locator: `getByRole('row').filter({ hasText: 'Bob' })`, indexBased: false },
    ]);
  });

  test('falls back to nth() with indexBased: true when rows share identical text', async ({ context }) => {
    const page = await context.newPage();
    await page.setContent(`<!doctype html><html><body>
      <table><tbody>
        <tr><td>Loading…</td></tr>
        <tr><td>Loading…</td></tr>
      </tbody></table>
    </body></html>`);

    const result = await evalDerive(page, 'tr', 2);
    expect(result.rows).toEqual([
      { locator: `getByRole('row').nth(0)`, indexBased: true },
      { locator: `getByRole('row').nth(1)`, indexBased: true },
    ]);
  });

  test('falls back to a shared stable CSS class when elements share no role (cards), preferring the more distinctive of several shared classes', async ({
    context,
  }) => {
    const page = await context.newPage();
    await page.setContent(`<!doctype html><html><body>
      <div class="card product-card">Widget A</div>
      <div class="card product-card">Widget B</div>
    </body></html>`);

    // Both "card" and "product-card" are shared, but "product-card" scores
    // higher under classifyCssStability (multi-word kebab-case vs. a single
    // short generic word), so it should win.
    const result = await evalDerive(page, '.card', 2);
    expect(result.baseLocator).toBe(`locator('.product-card')`);
    expect(result.rows).toHaveLength(2);
    expect(result.rows.every((r) => !r.indexBased)).toBe(true);
  });

  test('prefers a more stable shared class over a hashed/auto-generated one', async ({ context }) => {
    const page = await context.newPage();
    await page.setContent(`<!doctype html><html><body>
      <div class="css-a1b2c3d4 product-card">Widget A</div>
      <div class="css-a1b2c3d4 product-card">Widget B</div>
    </body></html>`);

    const result = await evalDerive(page, '.product-card', 2);
    expect(result.baseLocator).toBe(`locator('.product-card')`);
  });

  test('finds no pattern when picks share neither a role nor a class', async ({ context }) => {
    const page = await context.newPage();
    await page.setContent(`<!doctype html><html><body>
      <button>Save</button>
      <img alt="logo" src="x.png" />
    </body></html>`);

    const result = await evalDerive(page, 'button, img', 2);
    expect(result).toEqual({ baseLocator: null, rows: [] });
  });

  test('fewer than 2 picked elements yields no pattern', async ({ context }) => {
    const page = await context.newPage();
    await page.setContent(`<!doctype html><html><body><button>Save</button></body></html>`);
    const result = await evalDerive(page, 'button', 1);
    expect(result).toEqual({ baseLocator: null, rows: [] });
  });
});
