import { test, expect } from './fixtures.js';
import { derivePattern } from '../../src/content/multi-pick-derive.js';
import { domRoleOf } from '@piwitests/picker-dom';
import {
  isAutoGenerated,
  classifyCssStability,
  TAG_TO_ROLE,
  INPUT_TYPE_TO_ROLE,
} from '@piwitests/core/locator-generation';
import type { Page } from '@playwright/test';
import { playwrightLocator } from './playwright-locator.js';

const MAPS = { tagRoles: TAG_TO_ROLE, inputRoles: INPUT_TYPE_TO_ROLE };

/**
 * `derivePattern` nests every helper inside its own body (see that function's
 * doc comment): only its genuine cross-module imports — `domRoleOf`, `isAutoGenerated`,
 * `classifyCssStability` — need installing as globals first. The page it reads
 * is every element, open shadow roots included, and an element counts as
 * hidden when the browser does not render it or it sits under `aria-hidden`;
 * `multi-pick.spec.ts` checks the bundle's own wiring through the page engine.
 * `selector` picks in the document, or in the shadow root of `host`.
 */
async function evalDerive(
  page: Page,
  selector: string,
  count: number,
  host?: string,
): Promise<{ baseLocator: string | null; rows: { locator: string; indexBased: boolean }[] }> {
  await page.evaluate(
    ([roleSrc, autoGenSrc, stabilitySrc]) => {
      (globalThis as any).domRoleOf = new Function(`return (${roleSrc})`)();
      (globalThis as any).isAutoGenerated = new Function(`return (${autoGenSrc})`)();
      (globalThis as any).classifyCssStability = new Function(`return (${stabilitySrc})`)();
    },
    [domRoleOf.toString(), isAutoGenerated.toString(), classifyCssStability.toString()],
  );
  return page.evaluate(
    ([fnSrc, sel, n, maps, hostSel]) => {
      const derive = new Function(`return (${fnSrc})`)() as typeof derivePattern;
      const elements: Element[] = [];
      const visit = (root: Document | ShadowRoot) => {
        for (const el of root.querySelectorAll('*')) elements.push(el);
        for (const el of root.querySelectorAll('*')) if (el.shadowRoot) visit(el.shadowRoot);
      };
      visit(document);
      const isHidden = (el: Element) =>
        !el.checkVisibility({ visibilityProperty: true }) || !!el.closest('[aria-hidden="true"]');
      const scope = hostSel ? document.querySelector(hostSel)!.shadowRoot! : document;
      const picked = [...scope.querySelectorAll(sel)].slice(0, n);
      const result = derive(picked, maps as typeof MAPS, { elements, isHidden });
      return {
        baseLocator: result.baseLocator,
        rows: result.rows.map((r) => ({ locator: r.locator, indexBased: r.indexBased })),
      };
    },
    [derivePattern.toString(), selector, count, MAPS, host] as const,
  );
}

test.describe('derivePattern', () => {
  test('derives a getByRole(row) pattern with per-row hasText discriminators', async ({ context }) => {
    const page = await context.newPage();
    await page.setContent(`<!doctype html><html><body>
      <table><tbody>
        <tr><td>Alice - active</td></tr>
        <tr><td>Bob - active</td></tr>
        <tr><td>Carol - suspended</td></tr>
      </tbody></table>
    </body></html>`);

    const result = await evalDerive(page, 'tr', 2);
    expect(result.baseLocator).toBe(`getByRole('row')`);
    expect(result.rows).toEqual([
      { locator: `getByRole('row').filter({ hasText: 'Alice' })`, indexBased: false },
      { locator: `getByRole('row').filter({ hasText: 'Bob' })`, indexBased: false },
    ]);
  });

  test('falls back to nth() with indexBased: true when rows share identical text', async ({ context }) => {
    const page = await context.newPage();
    await page.setContent(`<!doctype html><html><body>
      <table><tbody>
        <tr><td>Loading…</td></tr>
        <tr><td>Loading…</td></tr>
      </tbody></table>
    </body></html>`);

    const result = await evalDerive(page, 'tr', 2);
    expect(result.rows).toEqual([
      { locator: `getByRole('row').nth(0)`, indexBased: true },
      { locator: `getByRole('row').nth(1)`, indexBased: true },
    ]);
  });

  test('falls back to a shared stable CSS class when elements share no role (cards), preferring the more distinctive of several shared classes', async ({
    context,
  }) => {
    const page = await context.newPage();
    await page.setContent(`<!doctype html><html><body>
      <div class="card product-card">Widget A</div>
      <div class="card product-card">Widget B</div>
    </body></html>`);

    // Both "card" and "product-card" are shared, but "product-card" scores
    // higher under classifyCssStability (multi-word kebab-case vs. a single
    // short generic word), so it should win.
    const result = await evalDerive(page, '.card', 2);
    expect(result.baseLocator).toBe(`locator('.product-card')`);
    expect(result.rows).toHaveLength(2);
    expect(result.rows.every((r) => !r.indexBased)).toBe(true);
  });

  test('prefers a more stable shared class over a hashed/auto-generated one', async ({ context }) => {
    const page = await context.newPage();
    await page.setContent(`<!doctype html><html><body>
      <div class="css-a1b2c3d4 product-card">Widget A</div>
      <div class="css-a1b2c3d4 product-card">Widget B</div>
    </body></html>`);

    const result = await evalDerive(page, '.product-card', 2);
    expect(result.baseLocator).toBe(`locator('.product-card')`);
  });

  test('counts nth() among the rows getByRole finds, a hidden one aside', async ({ context }) => {
    const page = await context.newPage();
    await page.setContent(`<!doctype html><html><body><ul>
      <li style="display:none">Loading…</li>
      <li id="first">Loading…</li>
      <li id="second">Loading…</li>
    </ul></body></html>`);
    const result = await evalDerive(page, 'li:not([style])', 2);
    expect(result.rows.map((r) => r.locator)).toEqual([`getByRole('listitem').nth(0)`, `getByRole('listitem').nth(1)`]);
    await expect(playwrightLocator(page, result.rows[0]!.locator)).toHaveAttribute('id', 'first');
    await expect(playwrightLocator(page, result.rows[1]!.locator)).toHaveAttribute('id', 'second');
  });

  test('counts the rows inside a web component, after the page’s own', async ({ context }) => {
    const page = await context.newPage();
    await page.setContent(`<!doctype html><html><body>
      <ul><li>Loading…</li></ul>
      <todo-list></todo-list>
      <script>
        customElements.define('todo-list', class extends HTMLElement {
          constructor() {
            super();
            this.attachShadow({ mode: 'open' }).innerHTML =
              '<ul><li id="first">Loading…</li><li id="second">Loading…</li></ul>';
          }
        });
      </script>
    </body></html>`);
    const result = await evalDerive(page, 'li', 2, 'todo-list');
    expect(result.rows.map((r) => r.locator)).toEqual([`getByRole('listitem').nth(1)`, `getByRole('listitem').nth(2)`]);
    await expect(playwrightLocator(page, result.rows[0]!.locator)).toHaveAttribute('id', 'first');
    await expect(playwrightLocator(page, result.rows[1]!.locator)).toHaveAttribute('id', 'second');
  });

  test('escapes a class that is not a plain CSS identifier', async ({ context }) => {
    const page = await context.newPage();
    await page.setContent(`<!doctype html><html><body>
      <div class="md:flex">Widget A</div>
      <div class="md:flex">Widget B</div>
    </body></html>`);
    const result = await evalDerive(page, 'div', 2);
    expect(result.baseLocator).toBe(`locator('.md\\\\:flex')`);
    await expect(playwrightLocator(page, result.baseLocator!)).toHaveCount(2);
    await expect(playwrightLocator(page, result.rows[1]!.locator)).toHaveText('Widget B');
  });

  test('finds no pattern when picks share neither a role nor a class', async ({ context }) => {
    const page = await context.newPage();
    await page.setContent(`<!doctype html><html><body>
      <button>Save</button>
      <img alt="logo" src="x.png" />
    </body></html>`);

    const result = await evalDerive(page, 'button, img', 2);
    expect(result).toEqual({ baseLocator: null, rows: [] });
  });

  test('fewer than 2 picked elements yields no pattern', async ({ context }) => {
    const page = await context.newPage();
    await page.setContent(`<!doctype html><html><body><button>Save</button></body></html>`);
    const result = await evalDerive(page, 'button', 1);
    expect(result).toEqual({ baseLocator: null, rows: [] });
  });
});
