// Conditional re-export: routes to the correct dialect at runtime.
// Both schemas are statically imported; the runtime selection is synchronous
// based on whether PIWI_DATABASE_URL is set.
// TypeScript type-checking uses the SQLite schema as the canonical reference.

import * as sqliteSchema from './schema.sqlite';
import * as pgSchema from './schema.pg';

// Pick the appropriate schema tables at module initialization time
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const schema: typeof sqliteSchema = (process.env.PIWI_DATABASE_URL ? pgSchema : sqliteSchema) as any;

export const {
  projects,
  testRuns,
  testSuites,
  testCases,
  testRunsCases,
  failureClusters,
  failureClusterAliases,
  failureClusterTestRoutes,
  quarantinedTests,
  clusterMergeSuggestions,
  failureDiagnoses,
  failureDiagnosisVersions,
  appSettings,
  files,
  traceResources,
  traceBlobs,
  traceBlobResources,
  tags,
  projectTags,
  markers,
  entityLinks,
  integrationConnections,
  projectIntegrations,
  integrationActions,
  users,
  apiKeys,
  extensionDeviceCodes,
  oauthClients,
  oauthGrants,
  oauthAuthorizationRequests,
  projectUrlPatterns,
  bugReports,
  bugReproductions,
  flakeExperiments,
  flakeArms,
  resourceFindings,
  resourceOccurrences,
  testRunResourceReports,
  networkRequests,
  accountTokens,
  notificationChannels,
  subscriptions,
  notificationDeliveries,
  healActions,
  groups,
  groupMembers,
  roleBindings,
  locatorSnapshots,
  locatorUsages,
  runLocatorBreaks,
  codeReach,
  casePayloads,
  testFunctions,
  testSelections,
  shareLinks,
  graphNodes,
  graphEdges,
  scenarioGaps,
  probes,
  analyticsDailyRollups,
  handbackOutcomes,
  handbackOutcomeRollups,
  mcpToolCalls,
  gateEvaluations,
  prFeedbackPosts,
  analyticsDashboards,
  reportSchedules,
  reportSnapshots,
} = schema;

// TypeScript type exports – always based on SQLite schema (the canonical reference)
export type {
  Project,
  NewProject,
  TestRun,
  NewTestRun,
  TestSuite,
  NewTestSuite,
  TestCase,
  NewTestCase,
  TestRunsCase,
  NewTestRunsCase,
  FailureCluster,
  NewFailureCluster,
  FailureClusterAlias,
  NewFailureClusterAlias,
  ClusterMergeSuggestion,
  NewClusterMergeSuggestion,
  FailureDiagnosis,
  NewFailureDiagnosis,
  AppSetting,
  NewAppSetting,
  File,
  NewFile,
  TraceResource,
  NewTraceResource,
  TraceBlob,
  NewTraceBlob,
  TraceBlobResource,
  NewTraceBlobResource,
  User,
  NewUser,
  ApiKey,
  NewApiKey,
  ExtensionDeviceCode,
  OAuthClient,
  OAuthGrant,
  OAuthAuthorizationRequest,
  ProjectUrlPattern,
  Tag,
  NewTag,
  ProjectTag,
  NewProjectTag,
  Marker,
  NewMarker,
  EntityLink,
  NewEntityLink,
  IntegrationConnection,
  NewIntegrationConnection,
  ProjectIntegration,
  NewProjectIntegration,
  IntegrationAction,
  NewIntegrationAction,
  NetworkRequest,
  NewNetworkRequest,
  AccountToken,
  NewAccountToken,
  NotificationChannel,
  NewNotificationChannel,
  Subscription,
  NewSubscription,
  NotificationDelivery,
  NewNotificationDelivery,
  HealActionRow,
  NewHealActionRow,
  Group,
  NewGroup,
  GroupMember,
  RoleBinding,
  NewRoleBinding,
  LocatorSnapshotRow,
  NewLocatorSnapshotRow,
  CasePayload,
  NewCasePayload,
  TestFunction,
  NewTestFunction,
  TestSelection,
  NewTestSelection,
  ShareLink,
  NewShareLink,
  GraphNode,
  NewGraphNode,
  GraphEdge,
  NewGraphEdge,
  ScenarioGap,
  NewScenarioGap,
  Probe,
  NewProbe,
  AnalyticsDashboard,
  ReportSchedule,
  ReportSnapshot,
} from './schema.sqlite';
