import { describe, test, expect } from 'vitest';
import {
  generateAlternatives,
  approximateAccessibleName,
  resolveAriaRole,
  headingLevel,
  isAutoGenerated,
  type ElementAttributes,
} from '#shared/locator-generation';

/**
 * Behavior tests for the browser-side alternative generator used by the
 * DOM-snapshot picker. Equivalence with the reporter's generator is pinned
 * separately in reporter-shared-drift.test.ts — these tests pin the behavior
 * itself: score tiers, uniqueness gating, and the getByLabel gate.
 */

function el(overrides: Partial<ElementAttributes> = {}): ElementAttributes {
  return {
    tagName: 'button',
    attributes: {},
    textContent: null,
    accessibleName: null,
    center: null,
    ...overrides,
  };
}

describe('generateAlternatives', () => {
  test('unique data-testid ranks first at score 100', () => {
    const alts = generateAlternatives(
      el({ attributes: { 'data-testid': 'pay-btn' }, accessibleName: 'Pay now', selectorCounts: { testId: 1 } }),
    );
    expect(alts[0]).toMatchObject({ locator: "getByTestId('pay-btn')", method: 'getByTestId', score: 100 });
    // Scores are sorted descending
    expect([...alts].sort((a, b) => b.score - a.score)).toEqual(alts);
  });

  test('an ambiguous data-testid (count > 1) is dropped', () => {
    const alts = generateAlternatives(
      el({ attributes: { 'data-testid': 'row' }, accessibleName: 'Open', selectorCounts: { testId: 4 } }),
    );
    expect(alts.some((a) => a.method === 'getByTestId')).toBe(false);
  });

  test('role + accessible name yields getByRole with the name', () => {
    const alts = generateAlternatives(el({ accessibleName: 'Pay now' }));
    expect(alts[0]).toMatchObject({
      locator: "getByRole('button', { name: 'Pay now' })",
      method: 'getByRole',
      args: { role: 'button', name: 'Pay now' },
      score: 90,
    });
  });

  test('a labeled input yields getByLabel; a placeholder-named one does not', () => {
    const labeled = generateAlternatives(
      el({ tagName: 'input', attributes: { type: 'email' }, accessibleName: 'Email address', hasLabel: true }),
    );
    expect(labeled.map((a) => a.method)).toContain('getByLabel');
    expect(labeled.find((a) => a.method === 'getByLabel')).toMatchObject({
      locator: "getByLabel('Email address')",
      score: 85,
    });

    // Accessible name approximated from the placeholder — must NOT claim a <label>
    const placeholderNamed = generateAlternatives(
      el({ tagName: 'input', attributes: { placeholder: 'Search' }, accessibleName: 'Search', hasLabel: false }),
    );
    expect(placeholderNamed.some((a) => a.method === 'getByLabel')).toBe(false);
    expect(placeholderNamed.some((a) => a.method === 'getByPlaceholder')).toBe(true);
  });

  test('heading level flows into getByRole args and locator text', () => {
    const alts = generateAlternatives(el({ tagName: 'h2', accessibleName: 'Overview' }));
    const heading = alts.find((a) => a.method === 'getByRole');
    expect(heading).toMatchObject({ args: { role: 'heading', name: 'Overview', level: 2 } });
    expect(heading!.locator).toContain('level: 2');
  });

  test('auto-generated or ambiguous ids are skipped; a stable unique id is kept', () => {
    const stable = generateAlternatives(el({ attributes: { id: 'pay' }, selectorCounts: { id: 1 } }));
    expect(stable.map((a) => a.locator)).toContain("locator('#pay')");

    const autogen = generateAlternatives(el({ attributes: { id: 'radix-:r3:' } }));
    expect(autogen.some((a) => a.locator.includes('#radix'))).toBe(false);

    const ambiguous = generateAlternatives(el({ attributes: { id: 'row' }, selectorCounts: { id: 2 } }));
    expect(ambiguous.some((a) => a.locator.includes('#row'))).toBe(false);
  });

  test('ancestor anchors produce chained name-free alternatives', () => {
    const alts = generateAlternatives(
      el({
        accessibleName: 'Delete',
        rolePosition: { role: 'button', count: 3, index: 1 },
        ancestors: [
          {
            tag: 'div',
            depth: 1,
            testId: 'cart-row',
            id: null,
            role: null,
            ariaLabel: null,
            scopedRoleCount: 1,
            testIdCount: 1,
          },
          {
            tag: 'section',
            depth: 2,
            testId: null,
            id: 'summary',
            role: null,
            ariaLabel: null,
            scopedRoleCount: 1,
            idCount: 1,
          },
        ],
      }),
    );
    expect(alts.find((a) => a.args.anchorTestId)).toMatchObject({
      locator: "getByTestId('cart-row').getByRole('button')",
      score: 72,
    });
    expect(alts.find((a) => a.args.anchorSelector)).toMatchObject({
      locator: "locator('#summary').getByRole('button')",
      score: 64,
    });
    // The anchored chains carry no name — they survive renames
    expect(alts.filter((a) => a.args.anchorTestId || a.args.anchorSelector).every((a) => !('name' in a.args))).toBe(
      true,
    );
  });

  test('structural alternatives are skipped when the element has its own unique testid', () => {
    const alts = generateAlternatives(
      el({
        attributes: { 'data-testid': 'pay-btn' },
        accessibleName: 'Pay',
        selectorCounts: { testId: 1 },
        rolePosition: { role: 'button', count: 1, index: 0 },
        ancestors: [
          {
            tag: 'div',
            depth: 1,
            testId: 'card',
            id: null,
            role: null,
            ariaLabel: null,
            scopedRoleCount: 1,
            testIdCount: 1,
          },
        ],
      }),
    );
    expect(alts.some((a) => a.args.anchorTestId)).toBe(false);
  });

  test('a document-unique role yields the bare name-free getByRole', () => {
    const alts = generateAlternatives(
      el({ accessibleName: 'Pay', rolePosition: { role: 'button', count: 1, index: 0 } }),
    );
    expect(alts.find((a) => a.method === 'getByRole' && !('name' in a.args))).toMatchObject({
      locator: "getByRole('button')",
      score: 58,
    });
  });

  test('class alternatives rank stable names above generated ones and drop ambiguous classes', () => {
    const alts = generateAlternatives(
      el({
        attributes: { class: 'submit-btn bg-red-500 css-x9k2p1' },
        selectorCounts: { classes: { 'submit-btn': 1, 'bg-red-500': 4, 'css-x9k2p1': 1 } },
      }),
    );
    const classLocators = alts.filter((a) => a.method === 'locator' && a.locator.includes('.'));
    expect(classLocators.map((a) => a.locator)).toEqual(["locator('.submit-btn')", "locator('.css-x9k2p1')"]);
    expect(classLocators[0]!.score).toBeGreaterThan(classLocators[1]!.score);
  });
});

describe('approximateAccessibleName', () => {
  test('prefers aria-label, then text, then title, then placeholder', () => {
    expect(approximateAccessibleName(el({ attributes: { 'aria-label': 'Close' }, textContent: 'X' }))).toBe('Close');
    expect(approximateAccessibleName(el({ textContent: 'Pay now', attributes: { title: 'Pay' } }))).toBe('Pay now');
    expect(approximateAccessibleName(el({ attributes: { title: 'Pay' } }))).toBe('Pay');
    expect(approximateAccessibleName(el({ attributes: { placeholder: 'Search' } }))).toBe('Search');
    expect(approximateAccessibleName(el())).toBeNull();
  });
});

describe('resolveAriaRole / headingLevel', () => {
  test('resolves implicit roles from tag and input type; explicit role wins', () => {
    expect(resolveAriaRole(el({ tagName: 'input', attributes: { type: 'email' } }))).toBe('textbox');
    expect(resolveAriaRole(el({ tagName: 'input', attributes: { type: 'checkbox' } }))).toBe('checkbox');
    expect(resolveAriaRole(el({ tagName: 'select', attributes: { multiple: '' } }))).toBe('listbox');
    expect(resolveAriaRole(el({ tagName: 'select' }))).toBe('combobox');
    expect(resolveAriaRole(el({ tagName: 'a', attributes: { href: '/x' } }))).toBe('link');
    expect(resolveAriaRole(el({ tagName: 'a' }))).toBeNull();
    expect(resolveAriaRole(el({ tagName: 'span', attributes: { role: 'tab' } }))).toBe('tab');
  });

  test('derives the heading level from the tag or aria-level', () => {
    expect(headingLevel(el({ tagName: 'h3' }), 'heading')).toBe(3);
    expect(headingLevel(el({ tagName: 'div', attributes: { 'aria-level': '4' } }), 'heading')).toBe(4);
    expect(headingLevel(el({ tagName: 'h3' }), 'button')).toBeNull();
  });
});

/**
 * A locator that matches several elements needs `.first()` or a filter before
 * it is usable, so it has to rank below anything known to be unique. Before
 * this, `getByRole('button', { name: 'Add to cart' })` scored 90 whether it
 * matched one element or twenty, and beat the scoped chain that actually
 * resolved to one — the generic suggestion nobody would paste into a suite.
 */
describe('generateAlternatives — ambiguity', () => {
  const twoCards = (roleName: number, text: number): ElementAttributes =>
    el({
      textContent: 'Add to cart',
      accessibleName: 'Add to cart',
      selectorCounts: { roleName, text },
      ancestors: [{ tag: 'section', depth: 1, testId: 'product-43', testIdCount: 1, scopedRoleCount: 1 }],
    });

  test('a unique scoped chain outranks a role+name that matches several elements', () => {
    const alts = generateAlternatives(twoCards(2, 2));
    expect(alts[0]!.locator).toBe("getByTestId('product-43').getByRole('button')");
    const roleName = alts.find((a) => a.locator.startsWith("getByRole('button'"))!;
    expect(roleName.score).toBe(45);
    expect(alts.find((a) => a.method === 'getByText')!.score).toBe(30);
  });

  test('the same element alone on the page keeps the role+name locator on top', () => {
    const alts = generateAlternatives(twoCards(1, 1));
    expect(alts[0]).toMatchObject({ locator: "getByRole('button', { name: 'Add to cart' })", score: 90 });
  });

  test('an unknown count is never penalised — an older capture must not be re-ranked on a guess', () => {
    const alts = generateAlternatives(
      el({ textContent: 'Add to cart', accessibleName: 'Add to cart', selectorCounts: {} }),
    );
    expect(alts.find((a) => a.method === 'getByRole')!.score).toBe(90);
    expect(alts.find((a) => a.method === 'getByText')!.score).toBe(75);
  });

  test('relative order among equally ambiguous candidates is preserved', () => {
    const alts = generateAlternatives(twoCards(3, 3));
    const roleName = alts.find((a) => a.method === 'getByRole' && !a.locator.includes('getByTestId'))!;
    const byText = alts.find((a) => a.method === 'getByText')!;
    expect(roleName.score).toBeGreaterThan(byText.score);
  });
});

/**
 * Plenty of apps identify a repeated card or row with a `data-*` hook and
 * nothing else — no testid, no id, no landmark role. Those ancestors used not
 * to be collected at all, so the leaf inside them got no scoped chain and fell
 * back to a locator matching every card on the page.
 */
describe('generateAlternatives — data-* anchors', () => {
  const card = (dataAttr: { name: string; value: string }, dataAttrCount = 1): ElementAttributes =>
    el({
      textContent: 'Add to cart',
      accessibleName: 'Add to cart',
      selectorCounts: { roleName: 2, text: 2 },
      ancestors: [{ tag: 'div', depth: 1, dataAttr, dataAttrCount, scopedRoleCount: 1 }],
    });

  test('an app-specific data-* hook anchors the chain and outranks the ambiguous leaf', () => {
    const alts = generateAlternatives(card({ name: 'data-product', value: '43' }));
    expect(alts[0]).toMatchObject({
      locator: `locator('[data-product="43"]').getByRole('button')`,
      method: 'getByRole',
      score: 60,
    });
    expect(alts[0]!.args).toMatchObject({ role: 'button', anchorSelector: '[data-product="43"]' });
  });

  test('test-oriented names score above app-specific ones, but under data-testid', () => {
    expect(generateAlternatives(card({ name: 'data-qa', value: 'row-7' }))[0]!.score).toBe(70);
    expect(generateAlternatives(card({ name: 'data-cy', value: 'row-7' }))[0]!.score).toBe(70);
    expect(generateAlternatives(card({ name: 'data-product', value: '43' }))[0]!.score).toBe(60);
  });

  test('a hook shared by several elements anchors nothing', () => {
    const alts = generateAlternatives(card({ name: 'data-kind', value: 'card' }, 4));
    expect(alts.some((a) => a.locator.includes('data-kind'))).toBe(false);
  });

  test('quotes in the value are escaped so the selector stays parseable', () => {
    const alts = generateAlternatives(card({ name: 'data-label', value: 'the "big" one' }));
    // Escaped twice on purpose: once for CSS, once for the TypeScript string
    // literal the expression is pasted into — evaluating it yields the CSS
    // selector [data-label="the \"big\" one"].
    expect(alts[0]!.locator).toBe(String.raw`locator('[data-label="the \\"big\\" one"]').getByRole('button')`);
  });

  test('only the closest usable data-* ancestor is used', () => {
    const alts = generateAlternatives(
      el({
        accessibleName: 'Add to cart',
        selectorCounts: { roleName: 2 },
        ancestors: [
          {
            tag: 'div',
            depth: 1,
            dataAttr: { name: 'data-product', value: '43' },
            dataAttrCount: 1,
            scopedRoleCount: 1,
          },
          {
            tag: 'div',
            depth: 2,
            dataAttr: { name: 'data-section', value: 'deals' },
            dataAttrCount: 1,
            scopedRoleCount: 1,
          },
        ],
      }),
    );
    expect(alts.filter((a) => a.locator.startsWith("locator('[data-"))).toHaveLength(1);
    expect(alts[0]!.locator).toContain('data-product');
  });
});

/**
 * A leaf with no role — a price `<span>`, a status badge — had no structural
 * alternatives at all, so on a list of cards the single suggestion was a bare
 * getByText matching every one of them.
 */
describe('generateAlternatives — text-scoped chains for role-less leaves', () => {
  const price = (anc: Partial<ElementAttributes['ancestors']>[number], text = 2): ElementAttributes =>
    el({
      tagName: 'span',
      textContent: '£49.99',
      selectorCounts: { text },
      ancestors: [{ tag: 'div', depth: 1, scopedTextCount: 1, ...anc }],
    });

  test('scopes the text to the nearest anchored ancestor', () => {
    const alts = generateAlternatives(price({ testId: 'row-keyboard', testIdCount: 1 }));
    expect(alts[0]).toMatchObject({
      locator: "getByTestId('row-keyboard').getByText('£49.99')",
      method: 'getByText',
      args: { text: '£49.99', anchorTestId: 'row-keyboard' },
      score: 68,
    });
  });

  test('every anchor kind is available, one notch below its getByRole counterpart', () => {
    expect(generateAlternatives(price({ testId: 'row', testIdCount: 1 }))[0]!.score).toBe(68);
    expect(
      generateAlternatives(price({ dataAttr: { name: 'data-qa', value: 'row' }, dataAttrCount: 1 }))[0]!.score,
    ).toBe(66);
    expect(generateAlternatives(price({ id: 'clearance', idCount: 1 }))[0]!.score).toBe(60);
    expect(
      generateAlternatives(price({ dataAttr: { name: 'data-product', value: '43' }, dataAttrCount: 1 }))[0]!.score,
    ).toBe(56);
    expect(generateAlternatives(price({ tag: 'nav', roleCount: 1 }))[0]).toMatchObject({
      locator: "getByRole('navigation').getByText('£49.99')",
      score: 51,
    });
  });

  test('an ancestor holding several matches of the text anchors nothing', () => {
    const alts = generateAlternatives(price({ testId: 'list', testIdCount: 1, scopedTextCount: 3 }));
    expect(alts.some((a) => a.locator.includes('getByTestId'))).toBe(false);
  });

  test('a unique text keeps the plain getByText on top — the chain is only a fallback', () => {
    const alts = generateAlternatives(price({ testId: 'row', testIdCount: 1 }, 1));
    expect(alts[0]).toMatchObject({ locator: "getByText('£49.99')", score: 75 });
    expect(alts[1]!.score).toBe(68);
  });

  test('a leaf that has a role gets role chains, not redundant text ones', () => {
    const alts = generateAlternatives(
      el({
        textContent: 'Add to cart',
        accessibleName: 'Add to cart',
        selectorCounts: { roleName: 2, text: 2 },
        ancestors: [{ tag: 'div', depth: 1, testId: 'row', testIdCount: 1, scopedRoleCount: 1, scopedTextCount: 1 }],
      }),
    );
    expect(alts.some((a) => a.method === 'getByText' && a.args.anchorTestId)).toBe(false);
    expect(alts[0]!.locator).toBe("getByTestId('row').getByRole('button')");
  });

  test('a leaf with its own unique testid needs no chain', () => {
    const alts = generateAlternatives(
      el({
        tagName: 'span',
        attributes: { 'data-testid': 'price' },
        textContent: '£49.99',
        selectorCounts: { testId: 1, text: 2 },
        ancestors: [{ tag: 'div', depth: 1, testId: 'row', testIdCount: 1, scopedTextCount: 1 }],
      }),
    );
    expect(alts.some((a) => a.args.anchorTestId)).toBe(false);
  });
});

/**
 * A cart list, a results table: nothing on the page carries a hook, and the
 * container role repeats once per row. The only thing that tells one row from
 * another is the text it holds.
 */
describe('generateAlternatives — filter({ hasText }) chains', () => {
  const row = (over: Partial<ElementAttributes['ancestors']>[number] = {}): ElementAttributes =>
    el({
      accessibleName: 'Remove',
      textContent: 'Remove',
      selectorCounts: { roleName: 3, text: 3 },
      ancestors: [
        {
          tag: 'li',
          depth: 1,
          scopedRoleCount: 1,
          roleCount: 3,
          filterText: 'Keyboard',
          filterRoleCount: 1,
          ...over,
        },
      ],
    });

  test('singles out the repeated container by the text it holds', () => {
    const alts = generateAlternatives(row());
    expect(alts[0]).toMatchObject({
      locator: "getByRole('listitem').filter({ hasText: 'Keyboard' }).getByRole('button')",
      method: 'getByRole',
      args: { role: 'button', anchorRole: 'listitem', anchorHasText: 'Keyboard' },
      score: 53,
    });
  });

  test('a text that does not narrow the container to one is not offered', () => {
    const alts = generateAlternatives(row({ filterRoleCount: 2 }));
    expect(alts.some((a) => a.locator.includes('filter('))).toBe(false);
  });

  test('a role-less leaf gets the same chain through its text, one notch lower', () => {
    const alts = generateAlternatives(
      el({
        tagName: 'span',
        textContent: '£49.99',
        selectorCounts: { text: 3 },
        ancestors: [
          { tag: 'li', depth: 1, scopedTextCount: 1, roleCount: 3, filterText: 'Keyboard', filterRoleCount: 1 },
        ],
      }),
    );
    expect(alts[0]).toMatchObject({
      locator: "getByRole('listitem').filter({ hasText: 'Keyboard' }).getByText('£49.99')",
      score: 49,
    });
  });

  test('a unique container role still prefers the plain chain, with the filter below it', () => {
    const alts = generateAlternatives(row({ roleCount: 1 }));
    expect(alts.find((a) => a.args.anchorRole && !a.args.anchorHasText)).toMatchObject({
      locator: "getByRole('listitem').getByRole('button')",
      score: 55,
    });
    expect(alts.find((a) => a.args.anchorHasText)!.score).toBe(53);
  });

  test('quotes in the filter text are escaped', () => {
    const alts = generateAlternatives(row({ filterText: "Bob's laptop" }));
    expect(alts[0]!.locator).toBe(
      String.raw`getByRole('listitem').filter({ hasText: 'Bob\'s laptop' }).getByRole('button')`,
    );
  });
});

/**
 * `word-digits` ids are ordinary record ids, often the one hook that makes a
 * repeated card addressable, so they do not read as framework output.
 */
describe('isAutoGenerated — semantic ids', () => {
  test('keeps ordinary record ids', () => {
    for (const id of ['product-43', 'row-7', 'user-12', 'item-999']) {
      expect(isAutoGenerated(id), id).toBe(false);
    }
  });

  test('still rejects long generated digit runs and framework patterns', () => {
    for (const id of ['item-1748291', 'radix-3ab', ':r3:', 'a1b2c3d4e5f6', 'ng-abc-1']) {
      expect(isAutoGenerated(id), id).toBe(true);
    }
  });

  test('rejects a widget-kind stem at any digit length — those are instance counters', () => {
    // `tab-2` is the second tab this render mounted; it renumbers when the set
    // changes, and being document-unique is all it is rather than evidence that
    // it means anything.
    for (const id of ['tab-2', 'panel-1', 'input-3', 'dialog-0', 'menu-11', 'Toggle-4']) {
      expect(isAutoGenerated(id), id).toBe(true);
    }
  });

  test('a domain stem that merely looks similar is still kept', () => {
    for (const id of ['table-3', 'invoice-2', 'card-9', 'order-1']) {
      expect(isAutoGenerated(id), id).toBe(false);
    }
  });
});

describe('generateAlternatives — ambiguity penalties beyond role and text', () => {
  const base = { tagName: 'input', accessibleName: null } as const;

  test('a placeholder repeated across the page ranks below a unique candidate', () => {
    const unique = generateAlternatives(
      el({ ...base, attributes: { placeholder: 'Search' }, selectorCounts: { placeholder: 1 } }),
    );
    const ambiguous = generateAlternatives(
      el({ ...base, attributes: { placeholder: 'Search' }, selectorCounts: { placeholder: 4 } }),
    );
    const scoreOf = (alts: ReturnType<typeof generateAlternatives>) =>
      alts.find((a) => a.method === 'getByPlaceholder')!.score;
    expect(scoreOf(unique)).toBe(80);
    expect(scoreOf(ambiguous)).toBeLessThan(49);
  });

  test('a repeated alt text and a repeated title are penalized the same way', () => {
    const alt = generateAlternatives(el({ tagName: 'img', attributes: { alt: 'Logo' }, selectorCounts: { alt: 3 } }));
    expect(alt.find((a) => a.method === 'getByAltText')!.score).toBeLessThan(49);

    const title = generateAlternatives(
      el({ tagName: 'span', attributes: { title: 'More' }, selectorCounts: { title: 3 } }),
    );
    expect(title.find((a) => a.method === 'getByTitle')!.score).toBeLessThan(49);
  });

  test('an unknown count still leaves the score untouched — no re-ranking on a guess', () => {
    const alts = generateAlternatives(el({ ...base, attributes: { placeholder: 'Search' } }));
    expect(alts.find((a) => a.method === 'getByPlaceholder')!.score).toBe(80);
  });
});
