import { describe, test, expect } from 'vitest';
import * as core from '@piwitests/core/locator-generation';
import { LOCATOR_BUILDER_METHODS } from '@piwitests/core/locator-methods';
// Imported from the reporter's *source* (vitest transpiles it), not dist/.
import * as reporter from '../../../../packages/reporter/src/internal/capture/locator-healing';

/**
 * The reporter bundles `@piwitests/core` rather than hand-mirroring it, so the
 * guarantee we want is *identity*: the reporter re-exports the exact core
 * functions, with no local copy that could drift. If someone re-implements one
 * of these in the reporter, the reference stops matching and this fails.
 */
describe('reporter re-exports @piwitests/core (no local re-implementation)', () => {
  test('locator-generation helpers are the same references as core', () => {
    expect(reporter.generateAlternatives).toBe(core.generateAlternatives);
    expect(reporter.resolveAriaRole).toBe(core.resolveAriaRole);
    expect(reporter.headingLevel).toBe(core.headingLevel);
    expect(reporter.classifyCssStability).toBe(core.classifyCssStability);
    expect(reporter.isAutoGenerated).toBe(core.isAutoGenerated);
    expect(reporter.approximateAccessibleName).toBe(core.approximateAccessibleName);
    expect(reporter.TAG_TO_ROLE).toBe(core.TAG_TO_ROLE);
    expect(reporter.INPUT_TYPE_TO_ROLE).toBe(core.INPUT_TYPE_TO_ROLE);
    expect(reporter.CAPTURED_ATTRIBUTES).toBe(core.CAPTURED_ATTRIBUTES);
  });

  test('the reporter method surface derives from the shared builder-method list', () => {
    expect(reporter.LOCATOR_METHODS).toEqual([...LOCATOR_BUILDER_METHODS]);
  });
});
