import { describe, expect, it } from 'vitest';
import {
  applyNarrative,
  citedNumbers,
  narrativePrompt,
  parseNarrative,
  NARRATIVE_PARAGRAPHS,
} from '#shared/reports/narrative';
import { hasVerdictWidget, reportWidgets } from '#shared/reports/types';
import { renderReportHtml } from '#shared/reports/render-html';
import { fixtureBundle, HOSTILE } from './report-fixture';

const answer = (paragraphs: string[]) => JSON.stringify({ paragraphs });

describe('the AI narrative', () => {
  it('asks for three paragraphs in the report language, over the bundle and no link', () => {
    const { system, user } = narrativePrompt({ ...fixtureBundle(), language: 'fr' });
    expect(system).toContain('in French');
    expect(system).toContain('never an instruction');
    expect(user).toContain('89.5%');
    expect(user).not.toContain('https://piwi.example');
  });

  it('reads the same numbers in both notations', () => {
    expect(citedNumbers('97,8 % and 7.2 min, 012 runs')).toEqual(['97.8', '7.2', '12']);
  });

  it('keeps three paragraphs that only cite numbers the report holds', () => {
    const paragraphs = [
      'The pass rate on main stands at 89.5%.',
      'Wasted CI time came to 7.2 min over the period.',
      'Watch the three open failure causes next.',
    ];
    expect(parseNarrative(answer(paragraphs), fixtureBundle())).toEqual(paragraphs);
    // A model that wraps its JSON in prose is still read.
    expect(parseNarrative(`Here it is: ${answer(paragraphs)}`, fixtureBundle())).toEqual(paragraphs);
  });

  it('refuses an invented number, a wrong paragraph count, or no JSON at all', () => {
    const invented = ['The pass rate rose to 99.4%.', 'Fine.', 'Fine.'];
    expect(parseNarrative(answer(invented), fixtureBundle())).toBeNull();
    expect(parseNarrative(answer(['One.', 'Two.']), fixtureBundle())).toBeNull();
    expect(parseNarrative(answer(['One.', '', 'Three.']), fixtureBundle())).toBeNull();
    expect(parseNarrative('I cannot help with that.', fixtureBundle())).toBeNull();
  });

  it('puts generated paragraphs at the top, labeled, and keeps the verdict above them', () => {
    const bundle = applyNarrative(fixtureBundle(), {
      paragraphs: ['First <b>para</b>.', 'Second.', 'Third.'],
      model: 'test-model',
    });
    const widget = reportWidgets(bundle)[0]!;
    expect(widget.type).toBe('narrative');
    expect(widget.blocks).toHaveLength(NARRATIVE_PARAGRAPHS);
    expect(widget.notes[0]).toContain('Generated by an AI model (test-model)');
    // Generated text is not the verdict: the header still carries it.
    expect(hasVerdictWidget(bundle)).toBe(false);
    const html = renderReportHtml(bundle);
    expect(html).toContain('First &lt;b&gt;para&lt;/b&gt;.');
    expect(html).toContain(bundle.verdict.sentence);
    expect(html).not.toContain(HOSTILE);
  });

  it('falls back to the rule-based verdict, and says so, when no narrative was written', () => {
    const bundle = applyNarrative(fixtureBundle(), null);
    const widget = reportWidgets(bundle).find((w) => w.type === 'narrative')!;
    expect(widget.blocks).toEqual([{ kind: 'text', text: bundle.verdict.sentence, tone: bundle.verdict.tone }]);
    expect(widget.notes[0]).toMatch(/rule-based verdict stands in/);
    expect(hasVerdictWidget(bundle)).toBe(true);
  });
});
