<script setup lang="ts">
/**
 * The report snapshots on the Reports page, newest first: what each quality
 * report covers, when it was generated, and how it was delivered.
 */
import type { ReportSnapshotSummary } from '#shared/handlers/reports';

defineProps<{ snapshots: ReportSnapshotSummary[] }>();

function delivery(s: ReportSnapshotSummary): string {
  if (s.scheduleId === null && s.deliveries.length === 0) return 'Generated by hand';
  if (s.deliveries.length === 0) return s.scheduleName ? `${s.scheduleName} · not sent` : 'Not sent';
  const sent = s.deliveries.filter((d) => d.status === 'sent').map((d) => d.channelName);
  const failed = s.deliveries.filter((d) => d.status === 'failed').map((d) => d.channelName);
  const pending = s.deliveries.filter((d) => d.status === 'pending').map((d) => d.channelName);
  const parts: string[] = [];
  if (sent.length) parts.push(`sent to ${sent.join(', ')}`);
  if (pending.length) parts.push(`sending to ${pending.join(', ')}`);
  if (failed.length) parts.push(`failed for ${failed.join(', ')}`);
  const text = parts.join('; ');
  return s.scheduleName ? `${s.scheduleName} · ${text}` : text.charAt(0).toUpperCase() + text.slice(1);
}
</script>

<template>
  <ul class="divide-y divide-default" data-testid="snapshot-list">
    <li v-for="s in snapshots" :key="s.id" class="py-3 min-w-0 space-y-0.5" :data-testid="`snapshot-${s.id}`">
      <NuxtLink :to="`/reports/${s.id}`" class="text-sm font-medium text-primary break-words hover:underline">
        {{ s.title }}
      </NuxtLink>
      <p class="text-xs text-muted break-words">{{ s.dashboardName }} · {{ s.period.label }}</p>
      <p class="text-xs text-muted break-words">
        <ClientOnly>{{ formatRelativeTime(s.generatedAt) }} · </ClientOnly>{{ delivery(s) }}
      </p>
    </li>
  </ul>
</template>
