import type { TourProfile } from './types';

/**
 * The demo's guided tours, one per role, in the order the prompt lists them.
 * Each stop opens a seeded screen and points at a `data-tour` element on it;
 * what it says is in the copy files (`copy.<code>.ts`), under the stop's id.
 */
export const TOUR_PROFILES: readonly TourProfile[] = [
  {
    id: 'developer',
    icon: 'i-lucide-code-xml',
    stops: [
      {
        id: 'failure',
        route: '/test-run-cases/37',
        expect: { execution: { id: 37, title: 'should complete checkout with credit card' } },
        target: 'situation',
        side: 'bottom',
        align: 'start',
        doc: 'guide/first-failure',
      },
      {
        id: 'evidence',
        route: '/test-run-cases/37',
        expect: { execution: { id: 37, title: 'should complete checkout with credit card' } },
        target: 'evidence',
        side: 'bottom',
        align: 'start',
        doc: 'features/evidence',
      },
      {
        id: 'locator',
        route: '/test-run-cases/533',
        expect: { execution: { id: 533, title: 'Button primary variant renders correctly' } },
        target: 'locator-fix',
        side: 'bottom',
        align: 'start',
        doc: 'features/locator-healing',
      },
      {
        id: 'diagnosis',
        route: '/failure-clusters/10',
        expect: { cluster: { id: 10, story: 'users-table-page-size' }, diagnosis: 'with-patch', fixLanded: true },
        target: 'diagnosis-fix',
        unfold: 'more-ways-to-fix',
        side: 'bottom',
        align: 'start',
        doc: 'features/ai-diagnosis',
      },
      { id: 'mcp', route: '/mcp', target: 'mcp-setup', side: 'bottom', align: 'start', doc: 'features/mcp' },
      {
        id: 'simulate',
        target: 'demo-simulator',
        side: 'bottom',
        align: 'center',
        doc: 'features/ui-overview#live-demo',
      },
    ],
  },
  {
    id: 'qa',
    icon: 'i-lucide-flask-conical',
    stops: [
      {
        id: 'inbox',
        route: '/',
        target: 'failure-inbox-row',
        side: 'bottom',
        align: 'start',
        doc: 'features/failure-clusters#the-failure-inbox',
      },
      {
        id: 'flaky',
        route: '/projects/1?tab=flaky-tests',
        expect: { project: { id: 1, name: 'e2e-checkout' } },
        target: 'flaky-test-row',
        side: 'bottom',
        align: 'start',
        doc: 'features/flaky-tests',
      },
      {
        id: 'suspects',
        route: '/test-cases/9?tab=flakiness',
        expect: { testCase: { id: 9, title: 'should apply discount code' }, lab: 'reproduced' },
        target: 'flake-suspects',
        side: 'bottom',
        align: 'start',
        doc: 'features/flaky-tests#suspects',
      },
      {
        id: 'slow',
        route: '/projects/1?tab=performance',
        expect: { project: { id: 1, name: 'e2e-checkout' } },
        target: 'slowest-tests',
        side: 'top',
        align: 'start',
        doc: 'features/slow-tests',
      },
      {
        id: 'lab',
        route: '/projects/3?tab=flake-lab',
        expect: { project: { id: 3, name: 'ui-components' } },
        target: 'flake-lab-tests',
        side: 'bottom',
        align: 'start',
        doc: 'features/flake-lab',
      },
      {
        id: 'gaps',
        route: '/projects/1?tab=gaps',
        expect: { project: { id: 1, name: 'e2e-checkout' } },
        target: 'feature-map',
        side: 'top',
        align: 'start',
        doc: 'features/scenario-gaps',
      },
    ],
  },
  {
    id: 'product',
    icon: 'i-lucide-clipboard-check',
    stops: [
      {
        id: 'health',
        route: '/',
        target: 'project-health',
        side: 'right',
        align: 'start',
        doc: 'features/ui-overview#home',
      },
      {
        id: 'analytics',
        route: '/analytics',
        target: 'analytics-headline',
        side: 'bottom',
        align: 'start',
        doc: 'features/analytics',
      },
      {
        id: 'dashboards',
        route: '/analytics/dashboards',
        target: 'team-dashboards',
        side: 'bottom',
        align: 'start',
        doc: 'features/dashboards',
      },
      {
        id: 'reports',
        route: '/reports',
        target: 'report-schedules',
        side: 'bottom',
        align: 'start',
        doc: 'features/quality-reports#report-schedules',
      },
      {
        id: 'issue',
        route: '/failure-clusters/3',
        expect: { cluster: { id: 3, story: 'auth-login-500' }, issue: { key: 'DEMO-42', status: 'In Progress' } },
        target: 'issue-line',
        side: 'bottom',
        align: 'start',
        doc: 'features/issue-tracking',
      },
      { id: 'personas', target: 'demo-personas', side: 'bottom', align: 'end', doc: 'operate/project-access' },
    ],
  },
  {
    id: 'platform',
    icon: 'i-lucide-server-cog',
    stops: [
      {
        id: 'timeline',
        route: '/test-runs/63?tab=workers',
        expect: { run: { id: 63, project: 'web-dashboard' } },
        target: 'run-timeline',
        side: 'bottom',
        align: 'start',
        doc: 'features/cpu-memory-disk',
      },
      {
        id: 'leaks',
        route: '/test-runs/62?tab=resources',
        expect: { run: { id: 62, project: 'web-dashboard' }, resources: 'leaky' },
        target: 'run-leaks',
        side: 'bottom',
        align: 'start',
        doc: 'features/resource-leaks',
      },
      {
        id: 'incident',
        route: '/test-runs/14',
        expect: { run: { id: 14, project: 'e2e-checkout' }, incident: true },
        target: 'run-incident',
        side: 'bottom',
        align: 'start',
        doc: 'features/environment-incidents',
      },
      {
        id: 'alerts',
        route: '/settings/notifications',
        target: 'notification-channels',
        side: 'bottom',
        align: 'start',
        doc: 'features/notifications',
      },
      {
        id: 'setup',
        route: '/setup',
        target: 'setup-ladder',
        side: 'bottom',
        align: 'start',
        doc: 'operate/capabilities',
      },
      {
        id: 'simulate',
        target: 'demo-simulator',
        side: 'bottom',
        align: 'center',
        doc: 'features/ui-overview#live-demo',
      },
    ],
  },
];
