import type { TourProfile } from './types';

/**
 * The demo's guided tours, one per role, in the order the prompt lists them.
 * Each stop opens a seeded screen and points at a `data-tour` element on it;
 * what it says is in the copy files (`copy.<code>.ts`), under the stop's id.
 */
export const TOUR_PROFILES: readonly TourProfile[] = [
  {
    id: 'developer',
    icon: 'i-lucide-code-xml',
    stops: [
      {
        id: 'failure',
        route: '/test-run-cases/37',
        target: 'situation',
        side: 'bottom',
        align: 'start',
        doc: 'guide/first-failure',
      },
      {
        id: 'evidence',
        route: '/test-run-cases/37',
        target: 'evidence',
        side: 'top',
        align: 'start',
        doc: 'features/evidence',
      },
      {
        id: 'locator',
        route: '/test-run-cases/533',
        target: 'locator-healing',
        side: 'top',
        align: 'start',
        doc: 'features/locator-healing',
      },
      {
        id: 'diagnosis',
        route: '/failure-clusters/10',
        expect: { cluster: { id: 10, story: 'users-table-page-size' }, diagnosis: 'with-patch', fixLanded: true },
        target: 'diagnosis',
        side: 'top',
        align: 'start',
        doc: 'features/ai-diagnosis',
      },
      { id: 'mcp', route: '/mcp', target: 'mcp-setup', side: 'top', align: 'start', doc: 'features/mcp' },
      {
        id: 'simulate',
        target: 'demo-simulator',
        side: 'bottom',
        align: 'center',
        doc: 'features/ui-overview#live-demo',
      },
    ],
  },
  {
    id: 'qa',
    icon: 'i-lucide-flask-conical',
    stops: [
      {
        id: 'inbox',
        route: '/',
        target: 'open-failures',
        side: 'top',
        align: 'start',
        doc: 'features/failure-clusters',
      },
      {
        id: 'flaky',
        route: '/projects/1?tab=flaky-tests',
        target: 'flaky-tests',
        side: 'top',
        align: 'start',
        doc: 'features/flaky-tests',
      },
      {
        id: 'suspects',
        route: '/test-cases/9?tab=flakiness',
        expect: { testCase: { id: 9, title: 'should apply discount code' }, lab: 'reproduced' },
        target: 'flakiness',
        side: 'top',
        align: 'start',
        doc: 'features/flake-lab',
      },
      {
        id: 'lab',
        route: '/projects/3?tab=flake-lab',
        expect: { project: { id: 3, name: 'ui-components' } },
        target: 'flake-lab',
        side: 'top',
        align: 'start',
        doc: 'features/flake-lab',
      },
      {
        id: 'slow',
        route: '/projects/1?tab=performance',
        target: 'slowest-tests',
        side: 'top',
        align: 'start',
        doc: 'features/slow-tests',
      },
      {
        id: 'gaps',
        route: '/projects/1?tab=gaps',
        target: 'test-gaps',
        side: 'top',
        align: 'start',
        doc: 'features/scenario-gaps',
      },
    ],
  },
  {
    id: 'product',
    icon: 'i-lucide-clipboard-check',
    stops: [
      {
        id: 'health',
        route: '/',
        target: 'project-health',
        side: 'bottom',
        align: 'start',
        doc: 'features/ui-overview',
      },
      {
        id: 'analytics',
        route: '/analytics',
        target: 'analytics-headline',
        side: 'bottom',
        align: 'start',
        doc: 'features/analytics',
      },
      {
        id: 'dashboards',
        route: '/analytics/dashboards',
        target: 'dashboards',
        side: 'bottom',
        align: 'start',
        doc: 'features/dashboards',
      },
      {
        id: 'reports',
        route: '/reports',
        target: 'quality-reports',
        side: 'bottom',
        align: 'start',
        doc: 'features/quality-reports',
      },
      {
        id: 'issue',
        route: '/failure-clusters/2',
        target: 'issue-line',
        side: 'bottom',
        align: 'start',
        doc: 'features/issue-tracking',
      },
      { id: 'personas', target: 'demo-personas', side: 'bottom', align: 'end', doc: 'operate/project-access' },
    ],
  },
  {
    id: 'platform',
    icon: 'i-lucide-server-cog',
    stops: [
      {
        id: 'timeline',
        route: '/test-runs/62?tab=workers',
        expect: { run: { id: 62, project: 'web-dashboard' }, resources: 'leaky' },
        target: 'run-timeline',
        side: 'top',
        align: 'start',
        doc: 'features/cpu-memory-disk',
      },
      {
        id: 'leaks',
        route: '/test-runs/62?tab=resources',
        expect: { run: { id: 62, project: 'web-dashboard' }, resources: 'leaky' },
        target: 'run-leaks',
        side: 'top',
        align: 'start',
        doc: 'features/resource-leaks',
      },
      {
        id: 'incident',
        route: '/test-runs/14',
        expect: { run: { id: 14, project: 'e2e-checkout' }, incident: true },
        target: 'run-incident',
        side: 'bottom',
        align: 'start',
        doc: 'features/environment-incidents',
      },
      {
        id: 'alerts',
        route: '/settings/notifications',
        target: 'notification-channels',
        side: 'bottom',
        align: 'start',
        doc: 'features/notifications',
      },
      { id: 'setup', route: '/setup', target: 'setup-ladder', side: 'top', align: 'start', doc: 'guide/ci' },
      {
        id: 'simulate',
        target: 'demo-simulator',
        side: 'bottom',
        align: 'center',
        doc: 'features/ui-overview#live-demo',
      },
    ],
  },
];
