import * as path from 'node:path';
import { fingerprintPresent, matchRenamedElement, parseAriaCandidates } from '@piwitests/core/locator-fingerprint';
import type { ElementFingerprint } from '@piwitests/core/locator-fingerprint';
import { LOCATOR_BUILDER_METHODS } from '@piwitests/core/locator-methods';

/**
 * Reporter-local locator healing.
 *
 * The pure surface — alternative generation, stability scoring, ARIA-role
 * resolution, the role maps and the captured-attribute whitelist — lives in
 * `@piwitests/core` (bundled into `dist/` at build time, so nothing
 * monorepo-relative leaks into the published package). It is re-exported from
 * here so existing importers (`capture-fixtures.ts`, `pick-on-failure.ts`, the
 * unit tests) keep importing it from this module.
 *
 * This module keeps only the reporter-only runtime: call-site capture (needs the
 * Node stack), snapshot dedupe, the fixture-proxy method surface, and the
 * failure-time locator suggestion + rendering.
 */

// ── Shared pure surface (single source of truth in @piwitests/core) ──────────
export {
  CAPTURED_ATTRIBUTES,
  INPUT_TYPE_TO_ROLE,
  TAG_TO_ROLE,
  approximateAccessibleName,
  classifyCssStability,
  generateAlternatives,
  headingLevel,
  isAutoGenerated,
  resolveAriaRole,
} from '@piwitests/core/locator-generation';
export type {
  AncestorAnchor,
  ElementAttributes,
  LocatorSnapshot,
  RankedLocator,
  RolePosition,
  SelectorCounts,
} from '@piwitests/core/locator-healing-types';

import type { LocatorSnapshot } from '@piwitests/core/locator-healing-types';

/**
 * Drop repeated captures of the same call site before attaching: a loop (or a
 * page-object method called repeatedly) produces one snapshot per action, but
 * the server keeps only the latest per location anyway. Keeps the last
 * element-bearing snapshot per location — falling back to the last placeholder
 * when no capture resolved, so the location still counts as "seen this run"
 * for the server's stale-location purge. Entries with no location pass through.
 */
export function dedupeSnapshotsByLocation(snaps: LocatorSnapshot[]): LocatorSnapshot[] {
  const lastWithElement = new Map<string, number>();
  const lastAny = new Map<string, number>();
  snaps.forEach((s, i) => {
    if (!s.location) return;
    lastAny.set(s.location, i);
    if (s.element) lastWithElement.set(s.location, i);
  });
  return snaps.filter((s, i) => {
    if (!s.location) return true;
    return (lastWithElement.get(s.location) ?? lastAny.get(s.location)) === i;
  });
}

// ── Playwright method surface (shared with the fixture proxy) ────────────────

/**
 * Page-level locator-building methods wrapped by the capture proxy. Imported by
 * both the capture fixtures (`capture-fixtures.ts`) and the dogfooding
 * `application/tests/fixtures.ts` so the two stay in sync (a prior drift missed
 * `scrollIntoViewIfNeeded`).
 */
export const LOCATOR_METHODS: string[] = [...LOCATOR_BUILDER_METHODS];

/**
 * Methods that can be chained onto a wrapped locator. Locator-creating chains
 * (those also in `LOCATOR_METHODS`) update the origin; positional/filter chains
 * (`first`, `nth`, `filter`, …) narrow without changing locator identity.
 */
export const CHAIN_METHODS: string[] = [
  'first',
  'nth',
  'last',
  'filter',
  'visible',
  'and',
  'or',
  'locator',
  'getByRole',
  'getByTestId',
  'getByText',
  'getByLabel',
  'getByPlaceholder',
  'getByAltText',
  'getByTitle',
];

/** Locator action methods that trigger element capture. */
export const ACTION_METHODS: string[] = [
  'click',
  'fill',
  'check',
  'uncheck',
  'selectOption',
  'dblclick',
  'tap',
  'hover',
  'press',
  'type',
  'pressSequentially',
  'clear',
  'setInputFiles',
  'dragTo',
  'focus',
  'blur',
  'scrollIntoViewIfNeeded',
  'dispatchEvent',
  'selectText',
  // Not an action, but a successful waitFor proves the element resolved — the
  // closest capture hook available for assertion-style usage of a locator.
  'waitFor',
];

/** Chain methods that create a new locator scope (origin tracks the chain call). */
export const LOCATOR_CREATING_CHAINS: ReadonlySet<string> = new Set(LOCATOR_METHODS);

/**
 * The private `Locator` method every web-first assertion funnels through:
 * `expect(locator).toBeVisible()` and friends all resolve to
 * `locator._expect(expression, { isNot, timeout, … })` on the locator instance
 * the test passed to `expect()` — which, under the capture fixtures, is the
 * wrapped proxy. Intercepting it is what lets assertion-only locators build
 * healing history. The funnel is unchanged across Playwright 1.40 → current;
 * if a future version renames it the interception silently never fires and
 * assertions behave exactly as without the proxy.
 */
export const EXPECT_METHOD = '_expect';

/**
 * Web-first assertion expressions whose PASS proves the target element
 * resolved — the assertion-side equivalent of a successful action, and the
 * capture hook for locators only ever used in `expect()`.
 *
 * Deliberately excluded:
 *  - absence assertions (`to.be.hidden`, `to.be.detached`): passing means the
 *    element may not exist at all — nothing to probe;
 *  - multi-element assertions (`to.have.count`, the `*.array` text/class
 *    forms, `to.have.values`): the single-element probe would only hit a
 *    strict-mode violation;
 *  - page-level assertions (`to.have.title`, `to.have.url`): they run on an
 *    internal `:root` locator that carries no healing value.
 * Negated calls (`.not.…`, `isNot: true`) are skipped at the call site — a
 * passing negative assertion proves nothing about the element resolving.
 */
export const EXPECT_CAPTURE_EXPRESSIONS: ReadonlySet<string> = new Set([
  'to.be.attached',
  'to.be.checked',
  'to.be.disabled',
  'to.be.editable',
  'to.be.empty',
  'to.be.enabled',
  'to.be.focused',
  'to.be.in.viewport',
  'to.be.readonly',
  'to.be.visible',
  'to.contain.class',
  'to.contain.text',
  'to.have.accessible.description',
  'to.have.accessible.error.message',
  'to.have.accessible.name',
  'to.have.attribute',
  'to.have.attribute.value',
  'to.have.class',
  'to.have.css',
  'to.have.id',
  'to.have.js.property',
  'to.have.role',
  'to.have.text',
  'to.have.value',
  'to.match.aria',
]);

// ── Accessible name extraction ───────────────────────────────────────────────

/**
 * Extract the accessible name from a YAML-like ariaSnapshot() output.
 *
 * Format example:
 *   - button "Submit order"
 *   - heading "Welcome, Alice"
 *   - textbox "Email" [ref=e12]
 *   - generic
 *
 * Returns the first quoted string after the role, or null if none found.
 */
export function extractAccessibleName(ariaSnapshot: string | null): string | null {
  if (!ariaSnapshot) return null;

  // Match the role line:  - role "name" [...]
  // The name is the first double-quoted string after the role keyword.
  const match = ariaSnapshot.match(/- \w+ "([^"]+)"/);
  if (match) return match[1];

  return null;
}

/** Tags whose accessible name comes from an associated `<label>`. */
export const FORM_FIELD_TAGS: ReadonlySet<string> = new Set(['input', 'select', 'textarea']);

/**
 * Roles whose accessible name is computed from the element's own content. For
 * these, an element carrying neither `aria-label` nor `aria-labelledby` is
 * named by its trimmed text — which the probe already returns.
 */
export const NAME_FROM_CONTENT_ROLES: ReadonlySet<string> = new Set([
  'button',
  'cell',
  'checkbox',
  'columnheader',
  'gridcell',
  'heading',
  'link',
  'menuitem',
  'menuitemcheckbox',
  'menuitemradio',
  'option',
  'radio',
  'row',
  'rowheader',
  'switch',
  'tab',
  'tooltip',
  'treeitem',
]);

/**
 * Caps the in-page probe applies to the strings below. A value sitting exactly
 * at its cap may have been cut short, and a truncated accessible name would
 * build a locator that matches nothing — so those fall through to the browser
 * instead of being trusted. Mirrors `probeElementAttrs`, which inlines its
 * limits because it is serialized into the page and cannot read a constant.
 */
const PROBE_TEXT_CAP = 80;
const PROBE_LABEL_TEXT_CAP = 120;

/** The subset of a probe result the accessible-name shortcut reads. */
export interface NameSource {
  tagName: string;
  attributes: Record<string, string | null>;
  textContent: string | null;
  labelText?: string | null;
}

/**
 * The accessible name when the probed attributes already settle it, or null
 * when only the browser can. Capture consults this before spending an
 * `ariaSnapshot()` round trip on an element: in each case below the name is
 * what the accessible-name computation would return anyway, so the round trip
 * would buy nothing.
 *
 * Deliberately narrow — anything outside these cases (an `aria-labelledby`
 * reference, an image named by `alt`, an element with no text) still goes to
 * the browser, because a wrong name here becomes a wrong `getByRole` locator.
 */
export function exactAccessibleName(attrs: NameSource, role: string | null): string | null {
  // Points at other elements — only the browser can resolve the reference.
  if (attrs.attributes['aria-labelledby']) return null;

  const ariaLabel = attrs.attributes['aria-label'];
  if (ariaLabel) return ariaLabel;

  if (FORM_FIELD_TAGS.has(attrs.tagName)) {
    const labelText = attrs.labelText;
    return labelText && labelText.length < PROBE_LABEL_TEXT_CAP ? labelText : null;
  }

  if (role && NAME_FROM_CONTENT_ROLES.has(role)) {
    const text = attrs.textContent;
    return text && text.length < PROBE_TEXT_CAP ? text : null;
  }

  return null;
}

// ── Runtime locator suggestion (the "element changed" case) ──────────────────

/** A failed locator action, used to suggest a fresh locator from the live page. */
export interface FailedLocatorInfo {
  method: string;
  args: unknown[];
  /** Test call site (`file:line:col`) of the failed action, when captured. */
  location?: string | null;
}

export interface LocatorSuggestion {
  /** The failed locator rendered as source, e.g. `getByText('Go to page')`. */
  failing: string;
  /** Fresh locator suggestions for the element's current identity, best first. */
  suggestions: string[];
}

/** Name-based locator methods — the only ones whose target can be re-found by accessible name. */
const NAME_BASED_METHODS = new Set([
  'getByText',
  'getByRole',
  'getByLabel',
  'getByPlaceholder',
  'getByTitle',
  'getByAltText',
]);

const escAttr = (s: string): string => s.replaceAll('\\', '\\\\').replaceAll("'", "\\'");

const SUGG_TEXT_ROLES = new Set([
  'button',
  'link',
  'heading',
  'menuitem',
  'tab',
  'option',
  'cell',
  'columnheader',
  'rowheader',
  'gridcell',
  'treeitem',
  'listitem',
  'checkbox',
  'radio',
  'switch',
]);
const SUGG_FIELD_ROLES = new Set(['textbox', 'combobox', 'searchbox', 'spinbutton', 'slider']);

/** Extract the role (for getByRole), targeted accessible name, and heading level from a failed locator's args. */
function failedNameAndRole(failed: FailedLocatorInfo): {
  role: string | null;
  name: string | null;
  level: number | null;
} {
  if (failed.method === 'getByRole') {
    const role = typeof failed.args[0] === 'string' ? (failed.args[0] as string) : null;
    const opts = failed.args[1] as Record<string, unknown> | undefined;
    const name = opts && typeof opts.name === 'string' ? (opts.name as string) : null;
    const level = opts && typeof opts.level === 'number' ? (opts.level as number) : null;
    return { role, name, level };
  }
  const first = failed.args.find((a) => typeof a === 'string');
  return { role: null, name: typeof first === 'string' ? (first as string) : null, level: null };
}

/** Render the failed locator back to source for annotation/picker messages. */
export function renderFailing(failed: FailedLocatorInfo): string {
  const { role, name } = failedNameAndRole(failed);
  if (failed.method === 'getByRole') {
    return name
      ? `getByRole('${escAttr(role ?? '')}', { name: '${escAttr(name)}' })`
      : `getByRole('${escAttr(role ?? '')}')`;
  }
  return `${failed.method}('${escAttr(name ?? '')}')`;
}

/** Build fresh locator suggestions for a matched candidate, with the failed method's style first. */
function freshSuggestions(
  candidate: { role: string; name: string; level?: number | null },
  failedMethod: string,
): string[] {
  const out: string[] = [];
  const role = candidate.role;
  const name = candidate.name;
  const push = (s: string) => {
    if (!out.includes(s)) out.push(s);
  };

  const levelPart = candidate.level != null ? `, level: ${candidate.level}` : '';
  const roleLoc = `getByRole('${escAttr(role)}', { name: '${escAttr(name)}'${levelPart} })`;
  const textLoc = `getByText('${escAttr(name)}')`;
  const labelLoc = `getByLabel('${escAttr(name)}')`;

  // Same-style first: a broken getByText is re-suggested as getByText where viable.
  if (failedMethod === 'getByText' && SUGG_TEXT_ROLES.has(role)) push(textLoc);
  if (failedMethod === 'getByLabel' && SUGG_FIELD_ROLES.has(role)) push(labelLoc);

  push(roleLoc);
  if (SUGG_TEXT_ROLES.has(role)) push(textLoc);
  else if (SUGG_FIELD_ROLES.has(role)) push(labelLoc);

  return out;
}

/**
 * Best-effort runtime suggestion for a locator that matched nothing: find the
 * element on the *current* page that the failed locator most likely targeted
 * (by accessible name similarity, restricted to the failed role when given) and
 * return fresh locators for it.
 *
 * Unlike the server lookup this has no pre-captured fingerprint — only the
 * failed locator + the live page — so it's a hint, not a guarantee. Returns null
 * for non-name-based locators (testid/CSS), when the targeted name is still
 * present (so the failure wasn't a rename), or when no candidate is confident.
 */
export function suggestLocatorsFromAria(
  failed: FailedLocatorInfo,
  ariaSnapshot: string | null,
): LocatorSuggestion | null {
  if (!ariaSnapshot || !NAME_BASED_METHODS.has(failed.method)) return null;

  const { role, name, level } = failedNameAndRole(failed);
  if (!name) return null;

  const candidates = parseAriaCandidates(ariaSnapshot);
  if (candidates.length === 0) return null;

  // Element identity + rename matching are shared with the server healing path
  // (@piwitests/core); only the same-style suggestion rendering below is
  // reporter-specific.
  const fingerprint: ElementFingerprint = { role, name, level };

  // The targeted name is still on the page → not a rename, nothing to suggest.
  if (fingerprintPresent(fingerprint, candidates)) return null;

  const best = matchRenamedElement(fingerprint, candidates)?.candidate;
  if (!best || !best.name) return null;

  const suggestions = freshSuggestions({ role: best.role, name: best.name, level: best.level }, failed.method);
  if (suggestions.length === 0) return null;

  return { failing: renderFailing(failed), suggestions };
}

// ── Call-site capture ────────────────────────────────────────────────────────

/**
 * Capture the calling test's source location (`file:line:col`) from the current
 * stack, for stamping onto a locator snapshot. The path is made cwd-relative so
 * it matches the location format Playwright embeds in error messages — which is
 * what the server's exact-match healing lookup (`extractErrorLocation`) parses.
 *
 * Stamping at action *call* time (rather than correlating with `pw:api` step
 * indices at step *end* time) avoids three classes of misalignment: `pw:api`
 * steps with no wrapped locator (e.g. `page.keyboard.press`), cross-worker step
 * interleaving, and concurrent actions reordering by end time.
 *
 * Returns null when no user frame can be identified — the snapshot keeps
 * `location: null` and the server falls back to fingerprint / ARIA lookup.
 */
export function captureCallerLocation(stack: string = new Error().stack ?? ''): string | null {
  const lines = stack.split('\n');
  // The capture machinery's own frames sit at the top of the stack: this module
  // (locator-healing) then the single fixtures-proxy frame that called it. Skip
  // exactly those, so the first remaining frame is the real test call site. A
  // USER file named `fixtures.*` further down the stack must be kept, so the
  // fixtures-proxy frame is only skipped when it directly follows this module.
  let prevWasCaptureModule = false;
  // The file this very function lives in, learned from its own frame (the
  // first parseable one). In the published package that file is the tsup
  // bundle (`dist/index.js`), where the module-name rules below can never
  // match — but every frame in the same file as this function is capture
  // machinery by definition, never a user call site.
  let selfFile: string | null = null;
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i]!.trim();
    if (!line.startsWith('at')) continue;
    const m = line.match(/^at\s+(?:(.+?)\s+\()?(.+?):(\d+):(\d+)\)?$/);
    if (!m) {
      prevWasCaptureModule = false;
      continue;
    }
    let file = m[2]!;
    if (!file || file.startsWith('node:')) {
      prevWasCaptureModule = false;
      continue;
    }
    file = file.replace(/^file:\/\/\/?/, '');
    // Must look like a source file (has an extension).
    if (!/\.[a-z]+$/i.test(file)) {
      prevWasCaptureModule = false;
      continue;
    }
    // This function's own file — internal by definition, bundled or not. The
    // fixtures-proxy skip stays armed only in the unbundled layout (where the
    // proxy lives in a separate `capture-fixtures.*`/`fixtures.*` file); in
    // the bundle the proxy frame is this same file and is consumed right here.
    if (selfFile === null || file === selfFile) {
      selfFile ??= file;
      prevWasCaptureModule = /[\\/]locator-healing\.[a-z]+$/i.test(file);
      continue;
    }
    // This module — always an internal frame; remember it so the immediately
    // following fixtures-proxy frame can be skipped too.
    if (/[\\/]locator-healing\.[a-z]+$/i.test(file)) {
      prevWasCaptureModule = true;
      continue;
    }
    // The fixtures proxy that called us — `capture-fixtures.*` in this
    // package, `fixtures.*` in the dogfood mirror. Skip only when it directly
    // follows this module, so a user's own `fixtures.*` deeper down is kept.
    if (prevWasCaptureModule && /[\\/](?:capture-)?fixtures\.[a-z]+$/i.test(file)) {
      prevWasCaptureModule = false;
      continue;
    }
    if (/[\\/]node_modules[\\/]/.test(file)) {
      prevWasCaptureModule = false;
      continue;
    }
    let rel = file;
    try {
      rel = path.relative(process.cwd(), file);
    } catch {
      /* keep absolute if relative fails */
    }
    rel = rel.split(path.sep).join('/');
    if (rel.startsWith('./')) rel = rel.slice(2);
    return `${rel}:${m[3]!}:${m[4]!}`;
  }
  return null;
}
