/**
 * Locator stability: how likely a locator chain a test uses is to break for a
 * reason unrelated to what the test checks — a restyle, a wrapper added around
 * an element, an item added to a list, a copy edit, other data.
 *
 * Judged from the chain's text alone, with a few named rules, so every client
 * of the locator index (the browser extension on a live page, the dashboard's
 * Locators page) reads the same verdict without anything being stored. CSS and
 * XPath selectors are read by a small tokenizer, not a selector engine: it only
 * needs to see classes, ids, attributes, pseudo-classes and combinators.
 */
import {
  LOCATING_METHODS,
  tryParseLocatorChain,
  type LocatorArg,
  type LocatorCall,
  type LocatorChain,
} from './locator-chain';
import { classifyCssStability, isAutoGenerated } from './locator-generation';

/** `stable`: nothing to say. `watch`: could break, worth a look. `brittle`: breaks on unrelated changes. */
export type LocatorStabilityLevel = 'stable' | 'watch' | 'brittle';

export type LocatorStabilityRuleId =
  | 'position'
  | 'css-class'
  | 'css-structure'
  | 'xpath'
  | 'generated-id'
  | 'style-attribute'
  | 'long-text'
  | 'data-text'
  | 'deep-chain';

export interface LocatorStabilityRule {
  id: LocatorStabilityRuleId;
  /** A few words for lists and cards: `position`, `CSS class`. */
  label: string;
  /** The highest level the rule gives a chain. */
  level: Exclude<LocatorStabilityLevel, 'stable'>;
  /** What the rule catches and why that breaks. */
  description: string;
}

/** Every rule, in the order findings are listed. */
export const LOCATOR_STABILITY_RULES: readonly LocatorStabilityRule[] = [
  {
    id: 'position',
    label: 'position',
    level: 'brittle',
    description:
      'Picks an element by its order: `nth(1)` and beyond are brittle, `first()`, `last()` and `nth(0)` worth watching. An element added above it, or a list sorted another way, moves it.',
  },
  {
    id: 'css-class',
    label: 'CSS class',
    level: 'brittle',
    description:
      'Finds an element by a class. Utility, hashed and CSS-in-JS classes are brittle, and a named class is worth watching: classes change with the styling.',
  },
  {
    id: 'css-structure',
    label: 'CSS structure',
    level: 'brittle',
    description:
      'Depends on the document structure: a child or sibling combinator, `:nth-child()` and its kind, three or more selectors deep, or tags only. A wrapper added or moved breaks it.',
  },
  {
    id: 'xpath',
    label: 'XPath',
    level: 'brittle',
    description:
      'An absolute or indexed XPath is brittle, and any other XPath is worth watching: XPath follows the document structure.',
  },
  {
    id: 'generated-id',
    label: 'generated id',
    level: 'brittle',
    description:
      'An id a framework or a build generates (`radix-:r4:`, `input-1748291`), which changes from one render or build to the next.',
  },
  {
    id: 'style-attribute',
    label: 'style attribute',
    level: 'brittle',
    description: 'Matches the `style` or `class` attribute as a string, which any styling edit changes.',
  },
  {
    id: 'long-text',
    label: 'long text',
    level: 'watch',
    description: 'An exact string over 40 characters: copy changes long before behavior does.',
  },
  {
    id: 'data-text',
    label: 'number in text',
    level: 'watch',
    description:
      'A count, price, date, time or percentage inside an exact string (`Cart (3)`, `$19.99`), which changes with the data.',
  },
  {
    id: 'deep-chain',
    label: 'long chain',
    level: 'watch',
    description: 'More than three locating calls: each container is one more thing a change can break.',
  },
];

const RULES_BY_ID = new Map(LOCATOR_STABILITY_RULES.map((rule) => [rule.id, rule]));

/** The rule with this id. */
export function locatorStabilityRule(id: LocatorStabilityRuleId): LocatorStabilityRule {
  return RULES_BY_ID.get(id)!;
}

interface LocatorStabilityFinding {
  rule: LocatorStabilityRuleId;
  level: Exclude<LocatorStabilityLevel, 'stable'>;
  /** The part of the locator the rule caught: `nth(1)`, `.btn-primary`, `//div[2]`, `'Cart (3)'`. */
  detail: string;
}

export interface LocatorStability {
  /** The level of the worst finding; `stable` when there is none. */
  level: LocatorStabilityLevel;
  /** Brittle findings first, then in rule order. */
  findings: LocatorStabilityFinding[];
}

/** An exact string longer than this is `long-text`. */
const LONG_TEXT_CHARS = 40;
/** A chain with more locating calls than this is `deep-chain`. */
const DEEP_CHAIN_CALLS = 3;
/** Details longer than this are shortened. */
const DETAIL_CHARS = 48;

/** Numbers that come from data rather than from the interface's own words. */
const DATA_PATTERNS: readonly RegExp[] = [
  // Currency next to a number: $19.99, 19,99 €.
  /[$€£¥₹]\s?\d[\d.,]*|\d[\d.,]*\s?[$€£¥₹]/,
  // An amount with two decimals: 19.99, 19,99.
  /\d+[.,]\d{2}\b/,
  // A date: 2026-09-27, 27/09/2026, 27.09.26.
  /\b\d{1,4}[-/.]\d{1,2}[-/.]\d{1,4}\b/,
  // A time: 10:30.
  /\b\d{1,2}:\d{2}\b/,
  // A percentage: 45%.
  /\d\s?%/,
  // A count in brackets: Cart (3), Inbox [12].
  /[([]\s*\d+\s*[)\]]/,
  // A count of things: 3 items, 12 results, 2 of 5, 4 days ago.
  /\b\d+\s+(?:of\s+\d+|items?|results?|left|remaining|products?|orders?|messages?|notifications?|comments?|reviews?|selected|days?|hours?|minutes?|seconds?|ago)\b/i,
  // A long number: an id, an amount, a year.
  /\d{4,}/,
];

function shorten(text: string, max = DETAIL_CHARS): string {
  return text.length > max ? `${text.slice(0, max - 1)}…` : text;
}

function quoted(text: string): string {
  return `'${shorten(text.replace(/\s+/g, ' ').trim())}'`;
}

class Collector {
  readonly findings: LocatorStabilityFinding[] = [];
  private readonly seen = new Set<string>();

  add(rule: LocatorStabilityRuleId, level: LocatorStabilityFinding['level'], detail: string): void {
    const key = `${rule}\x00${detail}`;
    if (this.seen.has(key)) {
      // Keep the worse level when the same part is caught twice.
      if (level === 'brittle') {
        const existing = this.findings.find((f) => f.rule === rule && f.detail === detail);
        if (existing) existing.level = 'brittle';
      }
      return;
    }
    this.seen.add(key);
    this.findings.push({ rule, level, detail });
  }
}

/** An exact string an element is found by: its copy and the data inside it. */
function checkText(text: string, out: Collector): void {
  const normalized = text.replace(/\s+/g, ' ').trim();
  if (!normalized) return;
  if (normalized.length > LONG_TEXT_CHARS) out.add('long-text', 'watch', quoted(normalized));
  for (const pattern of DATA_PATTERNS) {
    const match = pattern.exec(normalized);
    if (match) {
      out.add('data-text', 'watch', quoted(normalized));
      break;
    }
  }
}

function stringArg(arg: LocatorArg | undefined): string | null {
  return arg?.type === 'string' ? arg.value : null;
}

function objectEntry(arg: LocatorArg | undefined, key: string): LocatorArg | undefined {
  return arg?.type === 'object' ? arg.entries.find(([k]) => k === key)?.[1] : undefined;
}

/** The options a `locator()` or `filter()` call takes: `hasText`, `hasNotText`, `has`, `hasNot`, `visible`. */
function checkFilterOptions(arg: LocatorArg | undefined, out: Collector): void {
  if (arg?.type !== 'object') return;
  for (const [key, value] of arg.entries) {
    if ((key === 'hasText' || key === 'hasNotText') && value.type === 'string') checkText(value.value, out);
    else if ((key === 'has' || key === 'hasNot') && value.type === 'chain') checkChain(value.chain, out, true);
  }
}

// ── Selectors ────────────────────────────────────────────────────────────────

/**
 * Split `text` on `separator` where it is not inside quotes, brackets or
 * parentheses. `separator` is a single character or `>>`.
 */
function splitTopLevel(text: string, separator: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let quote: string | null = null;
  let start = 0;
  for (let i = 0; i < text.length; i++) {
    const c = text[i]!;
    if (quote) {
      if (c === '\\') i++;
      else if (c === quote) quote = null;
      continue;
    }
    if (c === '"' || c === "'") quote = c;
    else if (c === '[' || c === '(') depth++;
    else if (c === ']' || c === ')') depth = Math.max(0, depth - 1);
    else if (depth === 0 && text.startsWith(separator, i)) {
      parts.push(text.slice(start, i));
      start = i + separator.length;
      i += separator.length - 1;
    }
  }
  parts.push(text.slice(start));
  return parts;
}

function unquote(text: string): string {
  const t = text.trim();
  return (t.startsWith('"') && t.endsWith('"')) || (t.startsWith("'") && t.endsWith("'")) ? t.slice(1, -1) : t;
}

/** One Playwright selector string, `>>` parts included. */
function checkSelector(selector: string, out: Collector): void {
  for (const raw of splitTopLevel(selector, '>>')) {
    const part = raw.trim();
    if (!part) continue;
    const engine = /^([a-z][a-z0-9-]*(?::[a-z-]+)?)=/i.exec(part);
    const body = engine ? part.slice(engine[0].length) : part;
    const name = engine?.[1]!.toLowerCase();
    if (name === 'nth') {
      const n = Number(body.trim());
      if (Number.isFinite(n)) out.add('position', n >= 1 ? 'brittle' : 'watch', `nth=${body.trim()}`);
    } else if (name === 'xpath' || (!name && /^\(*\.{0,2}\//.test(part))) {
      checkXPath(body.trim(), out);
    } else if (name === 'text') {
      checkText(unquote(body), out);
    } else if (name === 'id') {
      checkId(unquote(body), out);
    } else if (name === 'css' || !name) {
      checkCss(body, out);
    }
    // Other engines (`data-testid=`, `internal:…`, `visible=`, …) say nothing about stability.
  }
}

function checkXPath(xpath: string, out: Collector): void {
  const bare = xpath.replace(/^\(+/, '');
  const absolute = bare.startsWith('/') && !bare.startsWith('//');
  const indexed = /\[\s*(?:\d+|last\(\)|position\(\)[^\]]*)\s*\]/.test(xpath);
  out.add('xpath', absolute || indexed ? 'brittle' : 'watch', shorten(xpath));
}

function checkId(id: string, out: Collector): void {
  if (id && isAutoGenerated(id)) out.add('generated-id', 'brittle', `#${shorten(id)}`);
}

const STRUCTURAL_PSEUDOS = new Set([
  'nth-child',
  'nth-last-child',
  'nth-of-type',
  'nth-last-of-type',
  'first-child',
  'last-child',
  'first-of-type',
  'last-of-type',
  'only-child',
  'only-of-type',
]);
const TEXT_PSEUDOS = new Set(['has-text', 'text', 'text-is', 'text-matches']);
const NESTED_PSEUDOS = new Set(['has', 'is', 'not', 'where', 'matches']);

/** A CSS selector list, with Playwright's own pseudo-classes. */
function checkCss(selectorList: string, out: Collector): void {
  for (const complex of splitTopLevel(selectorList, ',')) {
    const selector = complex.trim();
    if (!selector) continue;
    const { compounds, combinators } = tokenizeComplex(selector);
    if (combinators.some((c) => c !== ' ')) {
      out.add('css-structure', 'brittle', shorten(selector));
    } else if (compounds.length >= 3) {
      out.add('css-structure', 'brittle', shorten(selector));
    } else if (compounds.length >= 2 && compounds.every((c) => /^(?:\*|[a-z][a-z0-9-]*)$/i.test(c))) {
      out.add('css-structure', 'brittle', shorten(selector));
    }
    for (const compound of compounds) checkCompound(compound, out);
  }
}

/** A complex selector as its compound selectors and the combinators between them (`' '` for a descendant). */
function tokenizeComplex(selector: string): { compounds: string[]; combinators: string[] } {
  const compounds: string[] = [];
  const combinators: string[] = [];
  let current = '';
  let depth = 0;
  let quote: string | null = null;
  let pending: string | null = null;
  const flush = () => {
    if (!current) return;
    if (pending !== null && compounds.length > 0) combinators.push(pending);
    else if (pending !== null && pending !== ' ') combinators.push(pending); // a leading `>` in `:has(> a)`
    compounds.push(current);
    current = '';
    pending = null;
  };
  for (let i = 0; i < selector.length; i++) {
    const c = selector[i]!;
    if (quote) {
      current += c;
      if (c === '\\' && i + 1 < selector.length) current += selector[++i];
      else if (c === quote) quote = null;
      continue;
    }
    if (c === '"' || c === "'") {
      quote = c;
      current += c;
    } else if (c === '[' || c === '(') {
      depth++;
      current += c;
    } else if (c === ']' || c === ')') {
      depth = Math.max(0, depth - 1);
      current += c;
    } else if (depth === 0 && c === '\\' && i + 1 < selector.length) {
      current += c + selector[++i];
    } else if (depth === 0 && (c === '>' || c === '+' || c === '~')) {
      flush();
      pending = c;
    } else if (depth === 0 && /\s/.test(c)) {
      flush();
      if (pending === null) pending = ' ';
    } else {
      current += c;
    }
  }
  flush();
  return { compounds, combinators };
}

/** One compound selector: a tag, ids, classes, attributes and pseudo-classes. */
function checkCompound(compound: string, out: Collector): void {
  let i = 0;
  const readName = (): string => {
    let name = '';
    while (i < compound.length) {
      const c = compound[i]!;
      if (c === '\\' && i + 1 < compound.length) {
        name += compound[i + 1];
        i += 2;
        continue;
      }
      if (/[.#[:\s>+~,()]/.test(c)) break;
      name += c;
      i++;
    }
    return name;
  };
  const readBalanced = (open: string, close: string): string => {
    // `compound[i]` is `open`; returns what is between it and its match.
    let depth = 0;
    let quote: string | null = null;
    const start = i + 1;
    for (; i < compound.length; i++) {
      const c = compound[i]!;
      if (quote) {
        if (c === '\\') i++;
        else if (c === quote) quote = null;
        continue;
      }
      if (c === '"' || c === "'") quote = c;
      else if (c === open) depth++;
      else if (c === close && --depth === 0) {
        i++;
        return compound.slice(start, i - 1);
      }
    }
    return compound.slice(start);
  };

  while (i < compound.length) {
    const c = compound[i]!;
    if (c === '#') {
      i++;
      checkId(readName(), out);
    } else if (c === '.') {
      i++;
      const cls = readName();
      if (cls) out.add('css-class', classifyCssStability(cls) <= 25 ? 'brittle' : 'watch', `.${shorten(cls)}`);
    } else if (c === '[') {
      checkAttribute(readBalanced('[', ']'), out);
    } else if (c === ':') {
      i++;
      if (compound[i] === ':') i++;
      const name = readName().toLowerCase();
      const arg = compound[i] === '(' ? readBalanced('(', ')') : null;
      if (STRUCTURAL_PSEUDOS.has(name))
        out.add('css-structure', 'brittle', `:${name}${arg !== null ? `(${arg})` : ''}`);
      else if (name === 'nth-match') out.add('position', 'brittle', `:nth-match(${shorten(arg ?? '')})`);
      else if (TEXT_PSEUDOS.has(name) && arg !== null && !/^\s*\//.test(arg)) checkText(unquote(arg), out);
      else if (NESTED_PSEUDOS.has(name) && arg !== null) checkCss(arg, out);
    } else {
      // The tag, or a character the reader does not know: skip over it.
      const before = i;
      readName();
      if (i === before) i++;
    }
  }
}

function checkAttribute(inside: string, out: Collector): void {
  const m = /^\s*([^\s~|^$*!=]+)\s*(?:[~|^$*!]?=\s*(.*?))?\s*(?:\s[is])?\s*$/is.exec(inside);
  if (!m) return;
  const name = m[1]!.toLowerCase();
  const value = m[2] !== undefined ? unquote(m[2]) : null;
  if (name === 'style' || name === 'class') out.add('style-attribute', 'brittle', `[${shorten(inside.trim())}]`);
  else if (name === 'id' && value) checkId(value, out);
}

// ── Chains ───────────────────────────────────────────────────────────────────

function checkCall(call: LocatorCall, out: Collector): void {
  const [first, second] = call.args;
  switch (call.method) {
    case 'getByRole': {
      const name = stringArg(objectEntry(second, 'name'));
      if (name !== null) checkText(name, out);
      break;
    }
    case 'getByText':
    case 'getByLabel':
    case 'getByPlaceholder':
    case 'getByAltText':
    case 'getByTitle': {
      const text = stringArg(first);
      if (text !== null) checkText(text, out);
      break;
    }
    case 'locator':
    case 'frameLocator': {
      const selector = stringArg(first);
      if (selector !== null) checkSelector(selector, out);
      else if (first?.type === 'chain') checkChain(first.chain, out, true);
      checkFilterOptions(second, out);
      break;
    }
    case 'filter':
      checkFilterOptions(first, out);
      break;
    case 'nth': {
      const n = first?.type === 'number' ? first.value : null;
      if (n !== null) out.add('position', n >= 1 ? 'brittle' : 'watch', `nth(${n})`);
      break;
    }
    case 'first':
    case 'last':
      out.add('position', 'watch', `${call.method}()`);
      break;
    case 'and':
    case 'or':
      if (first?.type === 'chain') checkChain(first.chain, out, true);
      break;
    // getByTestId, visible, contentFrame, owner: nothing to say.
  }
}

function checkChain(chain: LocatorChain, out: Collector, nested: boolean): void {
  const locating = chain.calls.filter((call) => LOCATING_METHODS.has(call.method)).length;
  if (!nested && locating > DEEP_CHAIN_CALLS) out.add('deep-chain', 'watch', `${locating} locating calls`);
  for (const call of chain.calls) checkCall(call, out);
}

const RULE_ORDER = new Map(LOCATOR_STABILITY_RULES.map((rule, i) => [rule.id, i]));

/**
 * How likely a chain is to break for a reason unrelated to what its test
 * checks. The level is the worst finding's: a stable container cannot save a
 * brittle target, and a brittle container breaks every chain inside it.
 */
export function assessLocatorChain(chain: LocatorChain): LocatorStability {
  const out = new Collector();
  checkChain(chain, out, false);
  const findings = out.findings.sort(
    (a, b) =>
      (a.level === b.level ? 0 : a.level === 'brittle' ? -1 : 1) || RULE_ORDER.get(a.rule)! - RULE_ORDER.get(b.rule)!,
  );
  const level: LocatorStabilityLevel = findings.some((f) => f.level === 'brittle')
    ? 'brittle'
    : findings.length > 0
      ? 'watch'
      : 'stable';
  return { level, findings };
}

/** {@link assessLocatorChain} for a locator expression; null when it does not parse. */
export function assessLocator(expr: string): LocatorStability | null {
  const chain = tryParseLocatorChain(expr);
  return chain ? assessLocatorChain(chain) : null;
}

/**
 * The findings as a short list of words, each rule once, brittle ones first:
 * `position · CSS class`. Empty for a stable chain.
 */
export function stabilityLabels(stability: LocatorStability, separator = ' · '): string {
  const labels: string[] = [];
  for (const finding of stability.findings) {
    const label = locatorStabilityRule(finding.rule).label;
    if (!labels.includes(label)) labels.push(label);
  }
  return labels.join(separator);
}
