/**
 * Locator generation — pure functions for building ranked alternative locators
 * from element attributes. The single source of truth shared by the server, the
 * dashboard SPA, the interactive DOM snapshot picker (which runs in the
 * browser), and the Playwright reporter (which bundles this at build time).
 */
import type {
  RankedLocator,
  ElementAttributes,
  SelectorCounts,
  RolePosition,
  AncestorAnchor,
} from './locator-healing-types';

export type { RankedLocator, ElementAttributes, SelectorCounts, RolePosition, AncestorAnchor };

// ── ARIA role resolution ─────────────────────────────────────────────────────

/** Implicit ARIA role for an HTML tag (when no explicit `role` is set). */
export const TAG_TO_ROLE: Record<string, string> = {
  a: 'link',
  button: 'button',
  nav: 'navigation',
  main: 'main',
  article: 'article',
  section: 'region',
  form: 'form',
  img: 'img',
  figure: 'figure',
  figcaption: 'caption',
  blockquote: 'blockquote',
  table: 'table',
  caption: 'caption',
  thead: 'rowgroup',
  tbody: 'rowgroup',
  tfoot: 'rowgroup',
  tr: 'row',
  td: 'cell',
  ul: 'list',
  ol: 'list',
  li: 'listitem',
  dialog: 'dialog',
  output: 'status',
  progress: 'progressbar',
  meter: 'meter',
  textarea: 'textbox',
  h1: 'heading',
  h2: 'heading',
  h3: 'heading',
  h4: 'heading',
  h5: 'heading',
  h6: 'heading',
  details: 'group',
  summary: 'button',
  search: 'search',
};

/** Implicit ARIA role for an `<input>` keyed by its `type` attribute. */
export const INPUT_TYPE_TO_ROLE: Record<string, string> = {
  button: 'button',
  submit: 'button',
  reset: 'button',
  image: 'button',
  checkbox: 'checkbox',
  radio: 'radio',
  range: 'slider',
  search: 'searchbox',
  number: 'spinbutton',
  text: 'textbox',
  email: 'textbox',
  tel: 'textbox',
  url: 'textbox',
  password: 'textbox',
};

/** Element attributes captured by the probe. */
export const CAPTURED_ATTRIBUTES: string[] = [
  'id',
  'class',
  'name',
  'data-testid',
  'placeholder',
  'alt',
  'title',
  'aria-label',
  'aria-labelledby',
  'aria-level',
  'role',
  'type',
  'href',
  'multiple',
];

export function resolveAriaRole(attrs: ElementAttributes): string | null {
  const explicit = attrs.attributes['role'];
  if (explicit) return explicit;

  const tag = attrs.tagName;
  if (!tag) return null;

  if (tag === 'input') {
    const type = (attrs.attributes['type'] ?? 'text').toLowerCase();
    return INPUT_TYPE_TO_ROLE[type] ?? 'textbox';
  }

  if (tag === 'select') {
    return attrs.attributes['multiple'] != null ? 'listbox' : 'combobox';
  }

  if (tag === 'a') {
    return attrs.attributes['href'] != null ? 'link' : null;
  }

  return TAG_TO_ROLE[tag] ?? null;
}

export function headingLevel(attrs: ElementAttributes, role: string | null): number | null {
  if (role !== 'heading') return null;
  const tagMatch = attrs.tagName.match(/^h([1-6])$/);
  if (tagMatch) return Number(tagMatch[1]);
  const ariaLevel = attrs.attributes['aria-level'];
  if (ariaLevel && /^\d+$/.test(ariaLevel)) return Number(ariaLevel);
  return null;
}

// ── String utilities ────────────────────────────────────────────────────────

const attr = (a: ElementAttributes, key: string): string | null => a.attributes[key] || null;
const esc = (s: string): string => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
const escCssAttrValue = (s: string): string => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
const isCssSafeId = (id: string): boolean => /^[A-Za-z][A-Za-z0-9_-]*$/.test(id);

// ── CSS class stability ──────────────────────────────────────────────────────

export function classifyCssStability(className: string): number {
  if (/[a-f0-9]{8,}/i.test(className)) return 10;
  if (/^(?:css|sc|emotion|styled)-/i.test(className)) return 15;
  if (
    /^(bg|text|border|shadow|opacity|font|w-|h-|m[tblrxy]?-|p[tblrxy]?-|flex|grid|gap|rounded|absolute|relative|fixed|sticky|block|inline|hidden|overflow|z-|top-|right-|bottom-|left-|inset-|justify-|items-|self-|content-|order-|col-|row-)/.test(
      className,
    )
  )
    return 25;
  if (/__/.test(className) || /--/.test(className)) return 35;
  if (/^[a-z]+(-[a-z]+)+$/.test(className)) return 40;
  if (/^[a-z]+[A-Z][a-zA-Z]+$/.test(className)) return 40;
  if (className.includes('_')) return 15;
  if (/^[a-z]+-[a-z0-9]{5,}$/.test(className) && /[0-9]/.test(className)) return 15;
  return 15;
}

// ── Auto-generation detection ────────────────────────────────────────────────

export function isAutoGenerated(value: string): boolean {
  if (/^[a-f0-9]{8}-([a-f0-9]{4}-){3}[a-f0-9]{12}$/i.test(value)) return true;
  if (/^[a-f0-9]{8,}$/i.test(value)) return true;
  // `word-digits` used to be treated as machine output wholesale, which threw
  // away `product-43`, `row-7`, `user-12` — ordinary, stable, human-authored
  // ids, and often the only thing that makes a repeated card addressable. Only
  // long digit runs (`item-1748291`) read as generated; a short suffix is far
  // more likely to be a real record id, and it still has to be
  // document-unique before anything is built on it.
  if (/^[a-z]+-\d{4,}$/.test(value)) return true;
  // A widget-kind stem at any digit length is an instance counter, not a name:
  // `tab-2` is the second tab this render mounted and it renumbers when the set
  // changes, where `product-43` names product 43 for as long as it exists.
  // Inlined rather than hoisted to a module const — this function is
  // re-serialized into the page via `Function.prototype.toString()` (see
  // `apps/extension/src/content/multi-pick-derive.ts`), which carries a function's
  // own source text and nothing it closes over.
  if (
    /^(tab|panel|input|select|option|dialog|modal|popup|tooltip|menu|listbox|combobox|checkbox|radio|textarea|button|field|label|accordion|collapse|step|slider|toggle|switch|dropdown|overlay|portal|layer)-\d+$/i.test(
      value,
    )
  ) {
    return true;
  }
  if (/^(emotion-|styled-|css-|sc-)/.test(value)) return true;
  if (value.startsWith('ng-')) return true;
  if (/^(radix-|headlessui-|mui-|mantine-|chakra-)/i.test(value)) return true;
  if (/^:r[0-9a-z]+:$/i.test(value) || /^«r[0-9a-z]+»$/i.test(value)) return true;
  return false;
}

// ── Alternative generation ───────────────────────────────────────────────────

/**
 * `data-*` names that exist purely to be targeted by tests, so they score just
 * under `data-testid`. Any other author-chosen `data-*` still beats a bare
 * role anchor, but sits below `id`, which is at least guaranteed unique by the
 * HTML spec.
 */
const TEST_DATA_ATTRS = new Set(['data-test', 'data-test-id', 'data-qa', 'data-qa-id', 'data-cy', 'data-e2e']);

export function generateAlternatives(attrs: ElementAttributes): RankedLocator[] {
  const alts: RankedLocator[] = [];
  const seen = new Set<string>();
  const add = (loc: RankedLocator) => {
    if (!seen.has(loc.locator)) {
      seen.add(loc.locator);
      alts.push(loc);
    }
  };

  const { accessibleName } = attrs;
  const tag = attrs.tagName;
  const role = resolveAriaRole(attrs);
  const counts = attrs.selectorCounts as SelectorCounts | undefined;
  const isUnique = (n: number | undefined): boolean => n == null || n <= 1;
  /**
   * A locator matching more than one element is not usable as written — it
   * needs `.first()` or a filter — so it has to rank below anything known to
   * be unique. Subtracted rather than clamped, so the relative order among
   * equally ambiguous candidates survives; sized to drop the highest ambiguous
   * score (90) below the lowest unique one this generator emits (49, the
   * text-filtered chain). No penalty when the count is unknown — an older
   * capture must not be re-ranked on a guess.
   *
   * Applied to every candidate whose real match set the probe can count:
   * role+name, text, placeholder, alt and title. `getByLabel` is the one
   * exception — a label association is not expressible as an attribute
   * selector, so any count for it would be the guess this deliberately avoids.
   */
  const ambiguityPenalty = (n: number | undefined): number => (n != null && n > 1 ? 45 : 0);
  const text = attrs.textContent ? attrs.textContent.replace(/\s+/g, ' ').trim() : null;

  // 1. data-testid
  const testId = attr(attrs, 'data-testid');
  if (testId && isUnique(counts?.testId)) {
    add({
      locator: `getByTestId('${esc(testId)}')`,
      method: 'getByTestId',
      args: { testId },
      score: 100,
    });
  }

  const level = headingLevel(attrs, role);
  const levelPart = level != null ? `, level: ${level}` : '';
  const withLevel = (base: Record<string, unknown>): Record<string, unknown> =>
    level != null ? { ...base, level } : base;

  // 2. role + accessible name
  if (role && accessibleName) {
    add({
      locator: `getByRole('${role}', { name: '${esc(accessibleName)}'${levelPart} })`,
      method: 'getByRole',
      args: withLevel({ role, name: accessibleName }),
      score: 90 - ambiguityPenalty(counts?.roleName),
    });
  }

  // 3. role + explicit aria-label
  const ariaLabel = attr(attrs, 'aria-label');
  if (role && ariaLabel && ariaLabel !== accessibleName) {
    add({
      locator: `getByRole('${role}', { name: '${esc(ariaLabel)}'${levelPart} })`,
      method: 'getByRole',
      args: withLevel({ role, name: ariaLabel }),
      score: 85 - ambiguityPenalty(counts?.roleName),
    });
  }

  // 4. getByLabel
  if (accessibleName && ['input', 'select', 'textarea'].includes(tag)) {
    const label = attr(attrs, 'aria-label');
    const labelBacked = attrs.hasLabel === undefined ? true : attrs.hasLabel === true || label === accessibleName;
    if (labelBacked) {
      add({
        locator: `getByLabel('${esc(accessibleName)}')`,
        method: 'getByLabel',
        args: { label: accessibleName },
        score: 85,
      });
    }
  }

  // 5. getByPlaceholder
  const placeholder = attr(attrs, 'placeholder');
  if (placeholder) {
    add({
      locator: `getByPlaceholder('${esc(placeholder)}')`,
      method: 'getByPlaceholder',
      args: { placeholder },
      score: 80 - ambiguityPenalty(counts?.placeholder),
    });
  }

  // 6. getByText
  if (text && text.length < 80) {
    add({
      locator: `getByText('${esc(text)}')`,
      method: 'getByText',
      args: { text },
      score: 75 - ambiguityPenalty(counts?.text),
    });
  }

  // 7. locator('#id')
  const id = attr(attrs, 'id');
  if (id && !isAutoGenerated(id) && isUnique(counts?.id)) {
    const selector = isCssSafeId(id) ? `#${id}` : `[id="${escCssAttrValue(id)}"]`;
    add({
      locator: `locator('${esc(selector)}')`,
      method: 'locator',
      args: { selector },
      score: 65,
    });
  }

  // 8. locator('[name="..."]')
  const name = attr(attrs, 'name');
  if (name && isUnique(counts?.name)) {
    const selector = `[name="${escCssAttrValue(name)}"]`;
    add({
      locator: `locator('${esc(selector)}')`,
      method: 'locator',
      args: { selector },
      score: 60,
    });
  }

  // 9. getByAltText
  const alt = attr(attrs, 'alt');
  if (alt) {
    add({
      locator: `getByAltText('${esc(alt)}')`,
      method: 'getByAltText',
      args: { text: alt },
      score: 60 - ambiguityPenalty(counts?.alt),
    });
  }

  // 10. getByTitle
  const title = attr(attrs, 'title');
  if (title) {
    add({
      locator: `getByTitle('${esc(title)}')`,
      method: 'getByTitle',
      args: { title },
      score: 50 - ambiguityPenalty(counts?.title),
    });
  }

  // Structural alternatives — name-free, survive renames
  const hasOwnTestId = !!(testId && isUnique(counts?.testId));

  /**
   * Emit `<anchor>.<leaf>` chains for the nearest ancestor carrying each kind
   * of hook. `scopedCount` is what proves a chain resolves to exactly one
   * element: the leaf's role matches inside the ancestor for a role leaf, its
   * text matches for a role-less one. Scores are per leaf kind — a text leaf is
   * a weaker hook than a role one, so its chains sit a notch lower.
   */
  const addAnchoredChains = (
    leaf: { expr: string; method: string; args: Record<string, unknown>; role: string | null },
    scopedCount: (anc: AncestorAnchor) => number | undefined,
    scores: { testId: number; testData: number; id: number; data: number; role: number; filter: number },
  ): void => {
    let testIdAnchorDone = false;
    let idAnchorDone = false;
    let roleAnchorDone = false;
    let dataAnchorDone = false;
    let filterAnchorDone = false;
    for (const anc of attrs.ancestors ?? []) {
      if (scopedCount(anc) !== 1) continue;

      if (!testIdAnchorDone && anc.testId && anc.testIdCount === 1) {
        testIdAnchorDone = true;
        add({
          locator: `getByTestId('${esc(anc.testId)}').${leaf.expr}`,
          method: leaf.method,
          args: { ...leaf.args, anchorTestId: anc.testId },
          score: scores.testId,
        });
      }

      if (!idAnchorDone && anc.id && !isAutoGenerated(anc.id) && anc.idCount === 1) {
        idAnchorDone = true;
        const anchorSelector = isCssSafeId(anc.id) ? `#${anc.id}` : `[id="${escCssAttrValue(anc.id)}"]`;
        add({
          locator: `locator('${esc(anchorSelector)}').${leaf.expr}`,
          method: leaf.method,
          args: { ...leaf.args, anchorSelector },
          score: scores.id,
        });
      }

      if (!dataAnchorDone && anc.dataAttr && anc.dataAttrCount === 1) {
        dataAnchorDone = true;
        const { name, value } = anc.dataAttr;
        const anchorSelector = `[${name}="${escCssAttrValue(value)}"]`;
        add({
          locator: `locator('${esc(anchorSelector)}').${leaf.expr}`,
          method: leaf.method,
          args: { ...leaf.args, anchorSelector },
          score: TEST_DATA_ATTRS.has(name) ? scores.testData : scores.data,
        });
      }

      const ancestorRole = anc.role || TAG_TO_ROLE[anc.tag] || null;
      if (!roleAnchorDone && ancestorRole && ancestorRole !== leaf.role && anc.roleCount === 1) {
        roleAnchorDone = true;
        add({
          locator: `getByRole('${esc(ancestorRole)}').${leaf.expr}`,
          method: leaf.method,
          args: { ...leaf.args, anchorRole: ancestorRole },
          score: scores.role,
        });
      }

      // A card or row that repeats has no unique hook of its own — but the text
      // it holds names it, which is how a person would describe it anyway.
      if (!filterAnchorDone && ancestorRole && anc.filterText && anc.filterRoleCount === 1) {
        filterAnchorDone = true;
        add({
          locator: `getByRole('${esc(ancestorRole)}')` + `.filter({ hasText: '${esc(anc.filterText)}' }).${leaf.expr}`,
          method: leaf.method,
          args: { ...leaf.args, anchorRole: ancestorRole, anchorHasText: anc.filterText },
          score: scores.filter,
        });
      }
    }
  };

  if (role && !hasOwnTestId) {
    const rolePart = level != null ? `'${role}', { level: ${level} }` : `'${role}'`;
    const leafArgs = withLevel({ role });

    addAnchoredChains(
      { expr: `getByRole(${rolePart})`, method: 'getByRole', args: leafArgs, role },
      (anc) => anc.scopedRoleCount,
      { testId: 72, testData: 70, id: 64, data: 60, role: 55, filter: 53 },
    );

    // Name-free bare role
    const pos = attrs.rolePosition as RolePosition | undefined;
    if (pos && pos.role === role && (pos.count === 1 || (level != null && pos.levelCount === 1))) {
      add({
        locator: `getByRole(${rolePart})`,
        method: 'getByRole',
        args: leafArgs,
        score: 58,
      });
    }
  } else if (!role && text && text.length < 80 && !hasOwnTestId) {
    // A leaf with no role — a price `<span>`, a status badge — has nothing to
    // scope but its text. Without a chain the only candidate is a bare
    // getByText, which on a list of cards matches every one of them.
    addAnchoredChains(
      { expr: `getByText('${esc(text)}')`, method: 'getByText', args: { text }, role: null },
      (anc) => anc.scopedTextCount,
      { testId: 68, testData: 66, id: 60, data: 56, role: 51, filter: 49 },
    );
  }

  // CSS class-based
  const clsStr = attr(attrs, 'class');
  if (clsStr) {
    const countsClasses = counts?.classes as Record<string, number> | undefined;
    const classes = clsStr
      .split(/\s+/)
      .filter((c) => c.length > 1 && /^[A-Za-z_-][A-Za-z0-9_-]*$/.test(c) && isUnique(countsClasses?.[c]))
      .map((cls) => ({ cls, score: classifyCssStability(cls) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, 3);

    for (const { cls, score } of classes) {
      add({
        locator: `locator('.${esc(cls)}')`,
        method: 'locator',
        args: { selector: `.${cls}` },
        score,
      });
    }
  }

  return alts.sort((a, b) => b.score - a.score);
}

// ── Accessible name ──────────────────────────────────────────────────────────

/**
 * Approximate the accessible name from probed attributes, in the order the
 * accessible-name computation applies: `aria-labelledby` (resolved by the probe
 * into `labelText`), `aria-label`, then — for a form field — its `<label>`, or —
 * for anything else — its text, then `title` and `placeholder`.
 *
 * A form field is never named by its own text: a `<select>`'s text is its
 * options and a `<textarea>`'s is its value.
 */
export function approximateAccessibleName(attrs: ElementAttributes): string | null {
  const a = attrs.attributes;
  const labelText = attrs.labelText || null;
  if (a['aria-labelledby'] && labelText) return labelText;
  const ariaLabel = a['aria-label'];
  if (ariaLabel) return ariaLabel;
  if (['input', 'select', 'textarea'].includes(attrs.tagName)) {
    if (labelText) return labelText;
  } else if (attrs.textContent) {
    return attrs.textContent;
  }
  const title = a['title'];
  if (title) return title;
  const placeholder = a['placeholder'];
  if (placeholder) return placeholder;
  return null;
}
