import { getDatabase } from '../../../database';
import { requireAuth } from '../../../utils/auth';
import { requireRouteId } from '../../../utils/project-access';
import { reportActor, reportRoute } from '../../../utils/reports/context';
import { deleteReportSchedule } from '#shared/handlers/reports';

defineRouteMeta({
  openAPI: {
    tags: ['Reports'],
    summary: 'Delete a report schedule',
    description:
      'Deletes a report schedule. Its snapshots stay, like quality reports generated by hand. Its owner or an administrator; a global schedule, an administrator.',
    'x-required-roles': ['administrator', 'reporter'],
    parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'integer' } }],
  },
});

export default eventHandler(async (event) => {
  const user = await requireAuth(event);
  const id = requireRouteId(event, 'id', 'schedule ID');
  const db = await getDatabase();
  await reportRoute(() => deleteReportSchedule(db as any, id, reportActor(event, user as any)));
  return { success: true };
});
