/**
 * All test project names used across the functional test suite.
 *
 * Every name here is deleted before each test run by the cleanup endpoint
 * (`server/api/tests/cleanup.delete.ts`) so that projects can use static
 * names instead of `Date.now()` suffixes.
 *
 * When adding a new test that creates a project:
 * 1. Add a named entry to the `PROJECT` object below (alphabetically sorted by value)
 * 2. Import `PROJECT` from `#shared/test-project-names` (or `../../shared/test-project-names` from server code)
 * 3. Use `PROJECT.YOUR_KEY` in the test instead of a raw string
 * 4. The cleanup will automatically pick it up via `TEST_PROJECT_NAMES`
 */

export const PROJECT = {
  ANALYTICS_TEST: 'analytics-widgets-test',
  API_CREATED: 'api-created-project',
  API_KEY_SUBMIT: 'api-key-submit-test',
  AUTH_ROLE_CHECKS: 'auth-role-checks-test',
  AUTH_TEST: 'auth-test-project',
  BLOB_GZ: 'blob-gz-test-project',
  BLOCK_LAYOUT: 'block-layout-test',
  BLOCK_LAYOUT_VERSIONS: 'block-layout-versions-test',
  BROWSER_NOTIFY: 'browser-notify-test',
  CASE_FILES_LIVE: 'case-files-live-test',
  CLUSTER_MERGE: 'cluster-merge-test',
  CLUSTER_NAMING: 'cluster-naming-test',
  CLUSTER_PAGE_LAYOUT: 'cluster-page-layout-test',
  CLUSTER_SUGGEST: 'cluster-suggest-test',
  // Deliberately does not contain "projects" (case-insensitive substring) — the
  // sidebar's static "Projects" nav link is matched with getByRole('link', {
  // name: 'Projects' }) (no exact:true) elsewhere in the suite, which matches
  // accessible names by substring and would pick up a project literally named
  // "...projects...", causing a strict-mode violation in unrelated tests.
  DASHBOARD_OVERVIEW: 'dashboard-overview-test',
  DASHBOARD_PERF: 'dashboard-perf-tracking',
  DEFAULT_PROJECT: 'default-project',
  DELETE_TEST: 'delete-test-project',
  DESKTOP_LOCAL_IMPORT: 'desktop-local-import-test',
  DESKTOP_LOCAL_RUN: 'desktop-local-run-test',
  DESKTOP_REPRODUCE: 'desktop-reproduce-test',
  DIAGNOSE_STREAM: 'diagnose-stream-test',
  DOWNLOAD_TEST: 'download-test-project',
  DUP_UI: 'dup-ui-project',
  DUPLICATE: 'duplicate-project',
  EDIT_TEST: 'edit-test-project',
  EMPTY_METADATA: 'empty-metadata-test',
  EMPTY_PROJECT: 'empty-project',
  ENV_API: 'env-api-test',
  ENV_EMPTY: 'env-empty-test',
  ENV_LATEST_RUN: 'env-latestrun-test',
  ENV_MULTI: 'env-multi-test',
  ENV_NULL: 'env-null-test',
  ENV_RETRIEVAL: 'env-retrieval-test',
  ENV_SETUP: 'env-setup-test',
  ENV_STREAM_START: 'env-stream-start-test',
  ENV_UI: 'env-ui-test',
  ENV_UPLOAD: 'env-upload-test',
  EXPORT_OFFLINE: 'export-offline-test',
  AI_DIAGNOSIS: 'ai-diagnosis-test',
  AI_IMAGE_FALLBACK: 'ai-image-fallback-test',
  AI_LIVE_DIAGNOSIS: 'ai-live-diagnosis-test',
  AI_STEPS: 'ai-steps-coverage-test',
  EXTRACT_CASES: 'extract-cases-test',
  FAILURE_CLUSTERS: 'failure-clusters-test',
  FIXED_BEFORE: 'fixed-before-test',
  FIX_PLAN: 'fix-plan-test',
  FIX_VERIFICATION: 'fix-verification-test',
  FLAKY_BOARD: 'flaky-board-test',
  GATE_POLICY: 'gate-policy-test',
  GZIP_MIME: 'gzip-mime-test',
  GZIP_SERVE: 'gzip-serve-test-project',
  GZIP_TEST: 'gzip-test-project',
  HEARTBEAT_TEST: 'heartbeat-test',
  HTML_REPORT_SANDBOX: 'html-report-sandbox-test',
  HISTORY: 'history-test',
  HOME_OPEN_FAILURES: 'home-open-failures-test',
  IMPORT_BLOB: 'import-blob-test',
  IMPORT_BLOB_UI: 'import-blob-ui-test',
  IMPORT_TRACE: 'import-trace-test',
  IMPORT_TRACE_GROUP: 'import-trace-group-test',
  IMPORT_TRACE_RETRY: 'import-trace-retry-test',
  INCOMPLETE: 'incomplete-project',
  INLINE_HELP: 'inline-help-test',
  INSIGHTS_SPEC_HEALTH: 'insights-spec-health-test',
  INVALID_KEY: 'invalid-key-test',
  KEYBOARD_NAV: 'keyboard-nav-test',
  LABEL_OVERRIDE: 'label-override-project',
  LATEST_RUN_TEST: 'latest-run-test',
  LIST_VISIBLE: 'list-visible-project',
  MALFORMED: 'malformed-project',
  MCP_TEST: 'mcp-test-project',
  METADATA_RETRIEVAL: 'metadata-retrieval-test',
  METADATA_TEST: 'metadata-test-project',
  MINIMAL: 'minimal-project',
  MOBILE_RESPONSIVENESS: 'mobile-responsiveness-test',
  MULTI_REPORT: 'multi-report-project',
  NO_FILES: 'no-files-project',
  NO_METADATA: 'no-metadata-test',
  NO_OVERLAP: 'no-overlap',
  PERF_TEST: 'perf-test-project',
  PG_CONCURRENT: 'pg-concurrent-project',
  PG_TEST: 'pg-test-project',
  PROJECT_MEMBERS: 'project-members-test',
  QUARANTINE: 'quarantine-test',
  REGRESSION_CONTEXT: 'regression-context-test',
  REPORTER_API_KEY_E2E: 'reporter-api-key-e2e-test',
  REPORTER_API_KEY_LIB: 'reporter-api-key-lib-test',
  REPORTER_AUTH_LIB: 'reporter-auth-lib-test',
  REPORTER_AUTH: 'reporter-auth-test',
  REPORTER_FULL_AUTH: 'reporter-full-auth-test',
  REPORTER_LIVE_UPLOAD: 'reporter-live-upload-test',
  REPORTER_NO_AUTH: 'reporter-no-auth-test',
  REPORTS_DETAILS: 'reports-details-project',
  REVOKED_KEY: 'revoked-key-test',
  RUN_COMPARE: 'run-compare',
  RUN_LABEL: 'run-label-test',
  RUN_LOCATE: 'run-locate-test',
  RUN_PAGE_FILTERS: 'run-page-filters-test',
  RUN_SUMMARY_TEST: 'run-summary-test',
  SHARDING_TEST: 'sharding-test',
  SHARE_LINKS: 'share-links-e2e-test',
  STATS_TEST: 'stats-test-project',
  SUMMARY_FOLD: 'summary-fold-test',
  STORAGE_TEST: 'storage-test-project',
  STREAMING_DURATION: 'streaming-duration-test',
  STREAMING_FLAKY: 'streaming-flaky-test',
  STREAMING_TEST: 'streaming-test-project',
  TAG_ASSIGNMENT: 'tag-assignment-test-project',
  TEST_API: 'test-api-project',
  TEST_CASES_CATALOG: 'test-cases-catalog-test',
  TEST_FLAKY: 'test-flaky-project',
  TEST_PROJECT: 'test-project',
  TEST_RUN_CASE_PAGE: 'test-run-case-page-test',
  TEST_TAGS: 'test-tags-metadata-test',
  TRACE_DEDUP: 'trace-dedup-test',
  TRACE_INSIGHTS: 'trace-insights-test',
  TRACE_PREFLIGHT: 'trace-preflight-test',
  TRACE_RESOURCES: 'trace-resources-test',
  TRACES_API: 'traces-api-test',
  UI_CREATED: 'ui-created',
  UI_TEST: 'ui-test-project',
  UNRELATED: 'unrelated',
  UPLOAD_TEST: 'upload-test-project',
} as const;

type ProjectValue = (typeof PROJECT)[keyof typeof PROJECT];

export const TEST_PROJECT_NAMES: ProjectValue[] = Object.values(PROJECT);
