/**
 * The demo's report schedule and its two report snapshots, created through
 * the shared handlers when the in-browser database opens (the seed script
 * runs under plain Node and cannot render a quality report): a weekly
 * engineering schedule that fired last Monday, and an executive quality
 * report generated by hand.
 */
import { getAppSetting, setAppSetting } from '~~/server/utils/app-settings';
import { reportSchedules } from '~~/server/database/schema.sqlite';
import { parseAnalyticsScope } from '#shared/analytics/scope';
import {
  createReportSchedule,
  createReportSnapshot,
  parseScheduleBody,
  reportScheduleInputSchema,
  runReportSchedule,
} from '#shared/handlers/reports';
import { lastCompletePeriod, zonedInstant } from '#shared/reports/schedule';
import { addDays } from '#shared/analytics/period';
import type { DrizzleDB } from '#shared/handlers/db';
import { eq } from 'drizzle-orm';
import { DEMO_CHANNEL } from './api/demo-channel';

export const DEMO_REPORTS_SEEDED_SETTING = 'demo_report_snapshots_seeded_at';

export async function seedDemoReports(db: DrizzleDB): Promise<void> {
  if (await getAppSetting(db as any, DEMO_REPORTS_SEEDED_SETTING)) return;
  const now = Date.now();
  const timeZone = 'UTC';
  const channel = { id: DEMO_CHANNEL.id, name: DEMO_CHANNEL.name, type: DEMO_CHANNEL.type, userId: null };
  const actor = { id: null, isAdmin: true, authEnabled: false };
  // Created a month ago, so its last firing reports a whole week.
  const schedule = await createReportSchedule(
    db,
    parseScheduleBody(reportScheduleInputSchema, {
      name: 'Weekly engineering report',
      dashboard: 'engineering',
      cadence: 'weekly',
      anchor: 1,
      at: '08:00',
      channelIds: [channel.id],
    }),
    { actor, channels: [channel], access: 'all', timeZone, now: now - 30 * 86_400_000 },
  );
  const [row] = await db.select().from(reportSchedules).where(eq(reportSchedules.id, schedule.id));
  const timing = { cadence: 'weekly' as const, anchor: row!.anchor, at: row!.at, createdAt: row!.createdAt };
  const lastWeek = lastCompletePeriod(timing, now, timeZone);
  await runReportSchedule(db, row!, {
    access: 'all',
    timeZone,
    deliver: false,
    now,
    runAt: zonedInstant(addDays(lastWeek.to, 1), row!.at, timeZone).getTime(),
  });
  await createReportSnapshot(
    db,
    { dashboard: 'executive', scope: parseAnalyticsScope({ period: 'last-30d' }) },
    { access: 'all', timeZone, piwiVersion: 'demo', createdBy: null, now },
  );
  await setAppSetting(db as any, DEMO_REPORTS_SEEDED_SETTING, new Date(now).toISOString());
}
