import { describe, it, expect } from 'vitest';
import {
  generateAlternatives,
  classifyCssStability,
  isAutoGenerated,
  extractAccessibleName,
  approximateAccessibleName,
  resolveAriaRole,
  suggestLocatorsFromAria,
  type ElementAttributes,
} from '../src/internal/capture/locator-healing.js';

function makeAttrs(overrides: Partial<ElementAttributes & { attrs: Record<string, string | null> }> = {}) {
  const a = overrides.attrs ?? {};
  return {
    tagName: overrides.tagName ?? 'button',
    attributes: {
      id: a.id ?? null,
      class: a.class ?? null,
      name: a.name ?? null,
      'data-testid': a['data-testid'] ?? null,
      placeholder: a.placeholder ?? null,
      alt: a.alt ?? null,
      title: a.title ?? null,
      'aria-label': a['aria-label'] ?? null,
      role: a.role ?? null,
      type: a.type ?? null,
      href: a.href ?? null,
      value: a.value ?? null,
    },
    textContent: overrides.textContent ?? null,
    accessibleName: overrides.accessibleName ?? null,
    center: overrides.center ?? null,
  };
}

describe('generateAlternatives', () => {
  it('ranks data-testid highest (100)', () => {
    const attrs = makeAttrs({ attrs: { 'data-testid': 'submit-btn' } });
    const alts = generateAlternatives(attrs);
    expect(alts.length).toBeGreaterThan(0);
    expect(alts[0]!.method).toBe('getByTestId');
    expect(alts[0]!.score).toBe(100);
    expect(alts[0]!.locator).toBe("getByTestId('submit-btn')");
  });

  it('generates role + accessible name (90)', () => {
    const attrs = makeAttrs({ tagName: 'button', accessibleName: 'Submit order' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.locator).toContain("name: 'Submit order'");
  });

  it('generates role + aria-label when different from accessible name', () => {
    const attrs = makeAttrs({
      tagName: 'button',
      accessibleName: 'Submit order',
      attrs: { 'aria-label': 'Submit' },
    });
    const alts = generateAlternatives(attrs);
    const ariaAlt = alts.find((a) => a.method === 'getByRole' && a.score === 85);
    expect(ariaAlt).toBeTruthy();
  });

  it('skips role + aria-label when it equals accessible name', () => {
    const attrs = makeAttrs({
      tagName: 'button',
      accessibleName: 'Submit',
      attrs: { 'aria-label': 'Submit' },
    });
    const alts = generateAlternatives(attrs);
    // Should have role+accessibleName (90) but not a duplicate role+aria-label (85)
    const roleAlts = alts.filter((a) => a.method === 'getByRole');
    expect(roleAlts.length).toBe(1);
  });

  it('maps <input> to the textbox role, not the tag name', () => {
    const attrs = makeAttrs({ tagName: 'input', accessibleName: 'Email' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.locator).toBe("getByRole('textbox', { name: 'Email' })");
    expect(roleAlt!.args).toEqual({ role: 'textbox', name: 'Email' });
  });

  it('maps <input type=checkbox> to the checkbox role', () => {
    const attrs = makeAttrs({ tagName: 'input', attrs: { type: 'checkbox' }, accessibleName: 'Remember me' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.args.role).toBe('checkbox');
  });

  it('maps <select> to the listbox role', () => {
    const attrs = makeAttrs({ tagName: 'select', accessibleName: 'Country' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.args.role).toBe('listbox');
  });

  it('maps <textarea> to the textbox role', () => {
    const attrs = makeAttrs({ tagName: 'textarea', accessibleName: 'Comment' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.args.role).toBe('textbox');
  });

  it('maps <a href> to the link role', () => {
    const attrs = makeAttrs({ tagName: 'a', attrs: { href: '/home' }, accessibleName: 'Home' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.args.role).toBe('link');
  });

  it('maps <nav> to the navigation role', () => {
    const attrs = makeAttrs({ tagName: 'nav', accessibleName: 'Main' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.args.role).toBe('navigation');
  });

  it('maps <h1> to the heading role', () => {
    const attrs = makeAttrs({ tagName: 'h1', accessibleName: 'Welcome' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.args.role).toBe('heading');
  });

  it('does not generate getByRole for <div> (no implicit role)', () => {
    const attrs = makeAttrs({ tagName: 'div', accessibleName: 'Hello' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole');
    expect(roleAlt).toBeUndefined();
  });

  it('does not generate getByRole for <a> without href', () => {
    const attrs = makeAttrs({ tagName: 'a', accessibleName: 'Home' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole');
    expect(roleAlt).toBeUndefined();
  });

  it('prefers an explicit role attribute over the implicit tag role', () => {
    const attrs = makeAttrs({ tagName: 'div', attrs: { role: 'button' }, accessibleName: 'Submit' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.args.role).toBe('button');
  });

  it('generates getByLabel for form fields', () => {
    const attrs = makeAttrs({ tagName: 'input', accessibleName: 'Email' });
    const alts = generateAlternatives(attrs);
    const labelAlt = alts.find((a) => a.method === 'getByLabel');
    expect(labelAlt).toBeTruthy();
    expect(labelAlt!.score).toBe(85);
  });

  it('does not generate getByLabel for non-form elements', () => {
    const attrs = makeAttrs({ tagName: 'div', accessibleName: 'Hello' });
    const alts = generateAlternatives(attrs);
    const labelAlt = alts.find((a) => a.method === 'getByLabel');
    expect(labelAlt).toBeUndefined();
  });

  it('generates getByPlaceholder (80)', () => {
    const attrs = makeAttrs({ attrs: { placeholder: 'Enter your name' } });
    const alts = generateAlternatives(attrs);
    const placeholderAlt = alts.find((a) => a.method === 'getByPlaceholder');
    expect(placeholderAlt).toBeTruthy();
    expect(placeholderAlt!.score).toBe(80);
  });

  it('generates getByText for short text (75)', () => {
    const attrs = makeAttrs({ textContent: 'Click me' });
    const alts = generateAlternatives(attrs);
    const textAlt = alts.find((a) => a.method === 'getByText');
    expect(textAlt).toBeTruthy();
    expect(textAlt!.score).toBe(75);
  });

  it('skips getByText for long text (>80 chars)', () => {
    const attrs = makeAttrs({ textContent: 'a'.repeat(81) });
    const alts = generateAlternatives(attrs);
    const textAlt = alts.find((a) => a.method === 'getByText');
    expect(textAlt).toBeUndefined();
  });

  it('generates locator(#id) for stable ids (65)', () => {
    const attrs = makeAttrs({ attrs: { id: 'login-form' } });
    const alts = generateAlternatives(attrs);
    const idAlt = alts.find((a) => a.method === 'locator' && a.locator.startsWith("locator('#"));
    expect(idAlt).toBeTruthy();
    expect(idAlt!.score).toBe(65);
  });

  it('skips locator(#id) for auto-generated ids', () => {
    const attrs = makeAttrs({ attrs: { id: 'emotion-abc123def456' } });
    const alts = generateAlternatives(attrs);
    const idAlt = alts.find((a) => a.method === 'locator' && a.locator.startsWith("locator('#"));
    expect(idAlt).toBeUndefined();
  });

  it('generates locator([name="..."]) (60)', () => {
    const attrs = makeAttrs({ attrs: { name: 'username' } });
    const alts = generateAlternatives(attrs);
    const nameAlt = alts.find((a) => a.method === 'locator' && a.locator.includes('[name='));
    expect(nameAlt).toBeTruthy();
    expect(nameAlt!.score).toBe(60);
  });

  it('generates getByAltText (60)', () => {
    const attrs = makeAttrs({ attrs: { alt: 'Product photo' } });
    const alts = generateAlternatives(attrs);
    const altTextAlt = alts.find((a) => a.method === 'getByAltText');
    expect(altTextAlt).toBeTruthy();
    expect(altTextAlt!.score).toBe(60);
  });

  it('generates getByTitle (50)', () => {
    const attrs = makeAttrs({ attrs: { title: 'More info' } });
    const alts = generateAlternatives(attrs);
    const titleAlt = alts.find((a) => a.method === 'getByTitle');
    expect(titleAlt).toBeTruthy();
    expect(titleAlt!.score).toBe(50);
  });

  it('generates CSS class alternatives capped at 3', () => {
    const attrs = makeAttrs({ attrs: { class: 'a b c d e f' } });
    const alts = generateAlternatives(attrs);
    const cssAlts = alts.filter((a) => a.method === 'locator' && a.locator.startsWith("locator('."));
    expect(cssAlts.length).toBeLessThanOrEqual(3);
  });

  it('sorts alternatives by score descending', () => {
    const attrs = makeAttrs({
      tagName: 'button',
      accessibleName: 'Submit',
      attrs: {
        'data-testid': 'submit-btn',
        class: 'btn-primary',
        id: 'submit',
      },
    });
    const alts = generateAlternatives(attrs);
    for (let i = 1; i < alts.length; i++) {
      expect(alts[i]!.score).toBeLessThanOrEqual(alts[i - 1]!.score);
    }
  });

  it('does not generate duplicate locator expressions', () => {
    const attrs = makeAttrs({
      tagName: 'button',
      accessibleName: 'Click',
      textContent: 'Click',
    });
    const alts = generateAlternatives(attrs);
    const locators = alts.map((a) => a.locator);
    expect(new Set(locators).size).toBe(locators.length);
  });

  it('returns empty array for minimal attributes', () => {
    const attrs = makeAttrs();
    const alts = generateAlternatives(attrs);
    expect(alts.length).toBe(0);
  });

  it('escapes single quotes in locator expressions', () => {
    const attrs = makeAttrs({ attrs: { 'data-testid': "it's-working" } });
    const alts = generateAlternatives(attrs);
    expect(alts[0]!.locator).toBe("getByTestId('it\\'s-working')");
  });
});

describe('resolveAriaRole', () => {
  it('returns the explicit role attribute when present', () => {
    expect(resolveAriaRole(makeAttrs({ tagName: 'div', attrs: { role: 'navigation' } }))).toBe('navigation');
  });

  it('maps input to textbox by default', () => {
    expect(resolveAriaRole(makeAttrs({ tagName: 'input' }))).toBe('textbox');
  });

  it('maps input type variants', () => {
    expect(resolveAriaRole(makeAttrs({ tagName: 'input', attrs: { type: 'checkbox' } }))).toBe('checkbox');
    expect(resolveAriaRole(makeAttrs({ tagName: 'input', attrs: { type: 'radio' } }))).toBe('radio');
    expect(resolveAriaRole(makeAttrs({ tagName: 'input', attrs: { type: 'search' } }))).toBe('searchbox');
    expect(resolveAriaRole(makeAttrs({ tagName: 'input', attrs: { type: 'number' } }))).toBe('spinbutton');
    expect(resolveAriaRole(makeAttrs({ tagName: 'input', attrs: { type: 'range' } }))).toBe('slider');
  });

  it('maps structural tags to their implicit roles', () => {
    expect(resolveAriaRole(makeAttrs({ tagName: 'nav' }))).toBe('navigation');
    expect(resolveAriaRole(makeAttrs({ tagName: 'main' }))).toBe('main');
    expect(resolveAriaRole(makeAttrs({ tagName: 'select' }))).toBe('listbox');
    expect(resolveAriaRole(makeAttrs({ tagName: 'textarea' }))).toBe('textbox');
    expect(resolveAriaRole(makeAttrs({ tagName: 'h2' }))).toBe('heading');
    expect(resolveAriaRole(makeAttrs({ tagName: 'ul' }))).toBe('list');
    expect(resolveAriaRole(makeAttrs({ tagName: 'form' }))).toBe('form');
  });

  it('maps <a> to link only when href is present', () => {
    expect(resolveAriaRole(makeAttrs({ tagName: 'a', attrs: { href: '/x' } }))).toBe('link');
    expect(resolveAriaRole(makeAttrs({ tagName: 'a' }))).toBeNull();
  });

  it('returns null for tags with no implicit role', () => {
    expect(resolveAriaRole(makeAttrs({ tagName: 'div' }))).toBeNull();
    expect(resolveAriaRole(makeAttrs({ tagName: 'span' }))).toBeNull();
  });
});

describe('classifyCssStability', () => {
  it('scores hash-like suffixes as 10', () => {
    expect(classifyCssStability('btn-abc123')).toBeLessThanOrEqual(15);
    expect(classifyCssStability('xyz_a1b2c3d4')).toBeLessThanOrEqual(15);
  });

  it('scores CSS-in-JS prefixes as 15', () => {
    expect(classifyCssStability('css-xyz')).toBe(15);
    expect(classifyCssStability('sc-bdVaJa')).toBe(15);
    expect(classifyCssStability('emotion-cache')).toBe(15);
    expect(classifyCssStability('styled-button')).toBe(15);
  });

  it('scores utility classes as 25', () => {
    expect(classifyCssStability('bg-red-500')).toBe(25);
    expect(classifyCssStability('flex')).toBe(25);
    expect(classifyCssStability('p-4')).toBe(25);
    expect(classifyCssStability('rounded-lg')).toBe(25);
    expect(classifyCssStability('justify-between')).toBe(25);
  });

  it('scores BEM-style classes as 35', () => {
    expect(classifyCssStability('nav__item')).toBe(35);
    expect(classifyCssStability('btn--active')).toBe(35);
  });

  it('scores plain semantic classes as 40', () => {
    expect(classifyCssStability('submit-button')).toBe(40);
    expect(classifyCssStability('navItem')).toBe(40);
  });
});

describe('isAutoGenerated', () => {
  it('detects UUIDs', () => {
    expect(isAutoGenerated('550e8400-e29b-41d4-a716-446655440000')).toBe(true);
  });

  it('detects hex hashes (8+ chars)', () => {
    expect(isAutoGenerated('abc123def456')).toBe(true);
    expect(isAutoGenerated('feeddeadbeef')).toBe(true);
  });

  it('detects numeric-suffixed IDs', () => {
    expect(isAutoGenerated('btn-42')).toBe(true);
  });

  it('detects CSS-in-JS generated IDs', () => {
    expect(isAutoGenerated('emotion-xyz')).toBe(true);
    expect(isAutoGenerated('styled-button')).toBe(true);
    expect(isAutoGenerated('css-1a2b3c')).toBe(true);
  });

  it('detects Angular-style IDs', () => {
    expect(isAutoGenerated('ng-abc123')).toBe(true);
  });

  it('allows semantic IDs', () => {
    expect(isAutoGenerated('login-form')).toBe(false);
    expect(isAutoGenerated('submit-button')).toBe(false);
    expect(isAutoGenerated('user-email')).toBe(false);
  });
});

describe('extractAccessibleName', () => {
  it('extracts quoted name from aria snapshot', () => {
    expect(extractAccessibleName('- button "Submit order"')).toBe('Submit order');
    expect(extractAccessibleName('- heading "Welcome, Alice"')).toBe('Welcome, Alice');
    expect(extractAccessibleName('- textbox "Email" [ref=e12]')).toBe('Email');
  });

  it('returns null for elements without a name', () => {
    expect(extractAccessibleName('- generic')).toBe(null);
    expect(extractAccessibleName('- link')).toBe(null);
  });

  it('returns null for null input', () => {
    expect(extractAccessibleName(null)).toBe(null);
  });
});

describe('approximateAccessibleName', () => {
  it('prioritizes aria-label', () => {
    const attrs = makeAttrs({
      attrs: { 'aria-label': 'Close dialog', title: 'Close' },
      textContent: 'X',
    });
    expect(approximateAccessibleName(attrs)).toBe('Close dialog');
  });

  it('falls back to text content', () => {
    const attrs = makeAttrs({ textContent: 'Click here' });
    expect(approximateAccessibleName(attrs)).toBe('Click here');
  });

  it('falls back to title', () => {
    const attrs = makeAttrs({ attrs: { title: 'More info' } });
    expect(approximateAccessibleName(attrs)).toBe('More info');
  });

  it('falls back to placeholder', () => {
    const attrs = makeAttrs({ attrs: { placeholder: 'Search...' } });
    expect(approximateAccessibleName(attrs)).toBe('Search...');
  });

  it('returns null when nothing is available', () => {
    const attrs = makeAttrs();
    expect(approximateAccessibleName(attrs)).toBe(null);
  });
});

describe('suggestLocatorsFromAria', () => {
  // Canonical case: the button text changed from "Go to page" to "Open page"
  // but the test still says getByText('Go to page').
  const renamedAria = ['- navigation', '  - button "Open page"', '- contentinfo'].join('\n');

  it('suggests a fresh same-style locator for a renamed element', () => {
    const s = suggestLocatorsFromAria({ method: 'getByText', args: ['Go to page'] }, renamedAria);
    expect(s).not.toBeNull();
    expect(s!.failing).toBe("getByText('Go to page')");
    // Same family (getByText) first, then the role-based option.
    expect(s!.suggestions[0]).toBe("getByText('Open page')");
    expect(s!.suggestions).toContain("getByRole('button', { name: 'Open page' })");
  });

  it('matches within the failed role for getByRole', () => {
    const s = suggestLocatorsFromAria({ method: 'getByRole', args: ['button', { name: 'Go to page' }] }, renamedAria);
    expect(s!.suggestions[0]).toBe("getByRole('button', { name: 'Open page' })");
  });

  it('returns null when the targeted name is still present (not a rename)', () => {
    expect(suggestLocatorsFromAria({ method: 'getByText', args: ['Open page'] }, renamedAria)).toBeNull();
  });

  it('returns null for non-name-based locators (testid / CSS)', () => {
    expect(suggestLocatorsFromAria({ method: 'getByTestId', args: ['go'] }, renamedAria)).toBeNull();
    expect(suggestLocatorsFromAria({ method: 'locator', args: ['.btn'] }, renamedAria)).toBeNull();
  });

  it('returns null without an ARIA snapshot', () => {
    expect(suggestLocatorsFromAria({ method: 'getByText', args: ['Go to page'] }, null)).toBeNull();
  });

  it('does not guess among ambiguous same-role candidates with no overlap', () => {
    const aria = ['- button "Save"', '- button "Cancel"'].join('\n');
    expect(suggestLocatorsFromAria({ method: 'getByRole', args: ['button', { name: 'Delete' }] }, aria)).toBeNull();
  });

  it('suggests getByLabel for a renamed form field', () => {
    const aria = '- textbox "Email address"';
    const s = suggestLocatorsFromAria({ method: 'getByLabel', args: ['Email'] }, aria);
    expect(s!.suggestions[0]).toBe("getByLabel('Email address')");
  });
});
