<script setup lang="ts">
import type { ReportSnapshotView } from '#shared/handlers/reports';
import type { ReportFormat } from '#shared/reports/types';

const route = useRoute();
const id = computed(() => Number(route.params.id));

const {
  data: snapshot,
  pending,
  error,
} = await useFetch<ReportSnapshotView>(() => `/api/reports/snapshots/${id.value}`, {
  server: false,
  lazy: true,
});

useHead({ title: () => `${snapshot.value?.title ?? 'Quality report'} - Piwi Dashboard` });

// Share links need the server; the public demo has no share-link routes.
const isDemoMode = Boolean(useRuntimeConfig().public.demoMode);

const { download } = useDesktopDownload();
const base = computed(() => (useRuntimeConfig().app?.baseURL ?? '/').replace(/\/$/, ''));

const FORMATS: Array<{ format: ReportFormat; label: string; icon: string }> = [
  { format: 'pdf', label: 'PDF', icon: 'i-lucide-file-text' },
  { format: 'html', label: 'HTML', icon: 'i-lucide-file-code' },
  { format: 'md', label: 'Markdown', icon: 'i-lucide-file-type' },
  { format: 'csv', label: 'CSV', icon: 'i-lucide-sheet' },
  { format: 'json', label: 'JSON', icon: 'i-lucide-braces' },
];

async function downloadAs(format: ReportFormat) {
  const day = (snapshot.value?.generatedAt ?? new Date().toISOString()).slice(0, 10);
  await download(
    `${base.value}/api/reports/snapshots/${id.value}/export?format=${format}`,
    `piwi-quality-report-${snapshot.value?.dashboardRef ?? 'report'}-${day}.${format}`,
    { binary: format === 'pdf' },
  );
}

const downloadItems = computed(() => [
  FORMATS.map((f) => ({ label: f.label, icon: f.icon, onSelect: () => downloadAs(f.format) })),
]);

const deliveryLine = computed(() => {
  const s = snapshot.value;
  if (!s) return '';
  if (s.deliveries.length === 0) return s.scheduleId === null ? 'Generated by hand' : 'Not sent';
  return s.deliveries
    .map((d) => `${d.channelName}: ${d.status}${d.status === 'failed' && d.error ? ` (${d.error})` : ''}`)
    .join(' · ');
});
</script>

<template>
  <UDashboardPanel id="report-snapshot">
    <template #header>
      <UDashboardNavbar>
        <template #leading>
          <UDashboardSidebarCollapse />
          <BreadcrumbNav
            :items="[
              { label: 'Quality reports', icon: 'i-lucide-file-chart-column', to: '/reports' },
              { label: snapshot?.title ?? `Snapshot #${id}` },
            ]"
          />
        </template>
        <template v-if="snapshot" #right>
          <ShareLinksModal v-if="!isDemoMode" kind="report" :endpoint="`/api/reports/snapshots/${id}/share-links`" />
          <UDropdownMenu :items="downloadItems" :content="{ align: 'end' }">
            <UButton
              color="neutral"
              variant="outline"
              icon="i-lucide-download"
              trailing-icon="i-lucide-chevron-down"
              data-testid="snapshot-download"
            >
              <span class="hidden sm:inline">Download</span>
            </UButton>
          </UDropdownMenu>
        </template>
      </UDashboardNavbar>
    </template>

    <template #body>
      <LoadingState v-if="pending && !snapshot" />
      <ErrorState v-else-if="error" :text="`Couldn't open this quality report: ${errorMessage(error)}`" />
      <div v-else-if="snapshot" class="max-w-4xl space-y-4" data-shot="report-snapshot">
        <dl class="grid grid-cols-[6.5rem_1fr] gap-x-3 gap-y-1">
          <dt class="text-xs font-medium text-muted">Generated</dt>
          <dd class="text-xs text-muted"><ClientDate :date="snapshot.generatedAt" /></dd>
          <template v-if="snapshot.scheduleName">
            <dt class="text-xs font-medium text-muted">Schedule</dt>
            <dd class="text-xs text-muted break-words">{{ snapshot.scheduleName }}</dd>
          </template>
          <dt class="text-xs font-medium text-muted">Delivery</dt>
          <dd class="text-xs text-muted break-words" data-testid="snapshot-delivery">{{ deliveryLine }}</dd>
        </dl>
        <UCard>
          <ReportView :bundle="snapshot.bundle" />
        </UCard>
      </div>
    </template>
  </UDashboardPanel>
</template>
