import { domRoleOf, type DomRoleMaps } from '@piwitests/picker-dom';
import { isAutoGenerated, classifyCssStability } from '@piwitests/core/locator-generation';

interface PatternRow {
  element: Element;
  /** The full locator for this one element, e.g. `getByRole('row').filter({ hasText: 'Alice' })` or `getByRole('row').nth(2)`. */
  locator: string;
  /** True when this row could only be discriminated by position — Playwright will treat it as brittle to reordering. */
  indexBased: boolean;
}

/** The page as the derivation reads it: its elements and which ones `getByRole` skips. */
export interface PatternPage {
  /** Every element of the page, open shadow roots included, in the order Playwright returns them. */
  elements: readonly Element[];
  /** Hidden from the accessibility tree: `getByRole` skips it, so `.nth()` does not count it. */
  isHidden: (el: Element) => boolean;
}

export interface PatternResult {
  /** The shared base all rows narrow from, e.g. `getByRole('row')` or `locator('.card')` — null when the picks share no common role or class. */
  baseLocator: string | null;
  rows: PatternRow[];
}

/**
 * Derive a repeating-list locator pattern from 2-3 similar picked elements:
 * a shared base locator, then per element either `.filter({ hasText })`
 * using the shortest prefix of its own text that's unique among every
 * element sharing that base right now, or — when no prefix of its text is
 * unique (identical/empty rows) — `.nth(index)`, flagged `indexBased` so the
 * UI can show the "breaks on reorder" warning. The elements sharing the base
 * are the ones Playwright finds, in its order: for a role, those not hidden
 * from the accessibility tree; for a class, every element carrying it.
 *
 * Every helper is nested here rather than a module-level sibling: this gets
 * re-serialized via `Function.prototype.toString()` in tests (installing
 * `domRoleOf`/`isAutoGenerated`/`classifyCssStability` as globals first),
 * which only ever carries a function's own source text.
 */
export function derivePattern(picked: Element[], maps: DomRoleMaps, page: PatternPage): PatternResult {
  // Matches @piwitests/core's own `esc()` — every other generated locator in
  // this codebase is single-quoted, so this one shouldn't be the odd one out.
  function esc(s: string): string {
    return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  }

  function normalize(s: string): string {
    return s.replace(/\s+/g, ' ').trim();
  }

  function shortestUniqueHasText(el: Element, pool: Element[]): string | null {
    const words = normalize(el.textContent || '')
      .split(' ')
      .filter(Boolean);
    for (let n = 1; n <= words.length; n++) {
      const candidate = words.slice(0, n).join(' ');
      const needle = candidate.toLowerCase();
      const matches = pool.filter((other) =>
        normalize(other.textContent || '')
          .toLowerCase()
          .includes(needle),
      );
      if (matches.length === 1) return candidate;
    }
    return null;
  }

  function sharedStableClass(elements: Element[]): string | null {
    const classSets = elements.map((el) => new Set((el.getAttribute('class') || '').split(/\s+/).filter(Boolean)));
    const [first, ...rest] = classSets;
    if (!first) return null;
    const shared = [...first].filter((cls) => !isAutoGenerated(cls) && rest.every((s) => s.has(cls)));
    if (shared.length === 0) return null;
    shared.sort((a, b) => classifyCssStability(b) - classifyCssStability(a));
    return shared[0]!;
  }

  function rowsFor(baseLocator: string, pool: Element[]): PatternRow[] {
    return picked.map((element) => {
      const hasText = shortestUniqueHasText(element, pool);
      if (hasText != null) {
        return { element, locator: `${baseLocator}.filter({ hasText: '${esc(hasText)}' })`, indexBased: false };
      }
      const index = pool.indexOf(element);
      return { element, locator: index >= 0 ? `${baseLocator}.nth(${index})` : baseLocator, indexBased: true };
    });
  }

  if (picked.length < 2) return { baseLocator: null, rows: [] };

  const role = domRoleOf(picked[0]!, maps);
  if (role && picked.every((el) => domRoleOf(el, maps) === role)) {
    const pool = page.elements.filter((el) => domRoleOf(el, maps) === role && !page.isHidden(el));
    const baseLocator = `getByRole('${esc(role)}')`;
    return { baseLocator, rows: rowsFor(baseLocator, pool) };
  }

  const cls = sharedStableClass(picked);
  if (cls != null) {
    const pool = page.elements.filter((el) => el.classList.contains(cls));
    const baseLocator = `locator('.${esc(CSS.escape(cls))}')`;
    return { baseLocator, rows: rowsFor(baseLocator, pool) };
  }

  return { baseLocator: null, rows: [] };
}
