name: ci

on: pull_request

defaults:
  run:
    working-directory: ./application

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: ./application/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Install reporter dependencies
        working-directory: ./reporter
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps --only-shell

      - name: Run Playwright Tests
        run: npm test
